#!/usr/bin/env python3
"""
PARALLAX SDK — Alpha Generation, Factor Research, and Backtesting Engine
=========================================================================

Provides the research-side Python runtime for combining signals generated by
PARALLAX, constructing factors, evaluating alpha quality, and running compact
backtests without third-party dependencies.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from statistics import mean
from typing import Iterable, Optional

from .constants import PHI, PHI_INV, PHI_INV_2, PHI_INV_3


@dataclass
class PriceBar:
    """Compact OHLCV record with optional sentiment."""

    timestamp: int
    open: float
    high: float
    low: float
    close: float
    volume: float
    sentiment: float = 0.0


@dataclass
class Signal:
    """Single signal observation for a given horizon."""

    name: str
    score: float
    confidence: float = 1.0
    horizon: int = 1
    metadata: dict[str, float | str] = field(default_factory=dict)


@dataclass
class FactorInput:
    """Cross-sectional raw features used to construct factors."""

    asset: str
    price_to_book: float = 1.0
    earnings_yield: float = 0.0
    free_cash_flow_yield: float = 0.0
    return_21d: float = 0.0
    return_63d: float = 0.0
    return_126d: float = 0.0
    return_on_equity: float = 0.0
    gross_margin: float = 0.0
    leverage: float = 0.0
    macro_beta: float = 0.0
    inflation_sensitivity: float = 0.0
    yield_curve_sensitivity: float = 0.0
    alt_data_score: float = 0.0
    web_traffic_score: float = 0.0
    sentiment_score: float = 0.0


@dataclass
class AlphaCombinationResult:
    """Combined signal output plus diagnostics."""

    combined_signal: list[float]
    weights: dict[str, float]
    information_coefficients: dict[str, float]
    decay_by_horizon: dict[int, float]
    correlation_matrix: dict[str, dict[str, float]]


@dataclass
class BacktestResult:
    """Compact backtest report."""

    portfolio_returns: list[float]
    equity_curve: list[float]
    turnover: list[float]
    positions: list[dict[str, float]]
    sharpe: float
    cumulative_return: float
    max_drawdown: float
    hit_rate: float


@dataclass
class ResearchReport:
    """Research diagnostics for a factor or combined alpha."""

    attribution: dict[str, float]
    turnover_mean: float
    turnover_max: float
    robustness_mean_ic: float
    robustness_hit_rate: float
    train_ic: float
    test_ic: float
    decay_by_horizon: dict[int, float]


def _safe_mean(values: Iterable[float]) -> float:
    values = list(values)
    return mean(values) if values else 0.0


def _safe_std(values: Iterable[float]) -> float:
    values = list(values)
    if len(values) < 2:
        return 0.0
    mu = _safe_mean(values)
    variance = sum((value - mu) ** 2 for value in values) / len(values)
    return math.sqrt(max(variance, 0.0))


def _zscore(values: list[float]) -> list[float]:
    sigma = _safe_std(values)
    if sigma == 0.0:
        return [0.0 for _ in values]
    mu = _safe_mean(values)
    return [(value - mu) / sigma for value in values]


def _winsorize(values: list[float], limit: float = 3.0) -> list[float]:
    return [max(-limit, min(limit, value)) for value in values]


def _pearson(x: list[float], y: list[float]) -> float:
    if not x or not y or len(x) != len(y):
        return 0.0
    x_mu = _safe_mean(x)
    y_mu = _safe_mean(y)
    x_var = sum((value - x_mu) ** 2 for value in x)
    y_var = sum((value - y_mu) ** 2 for value in y)
    if x_var == 0.0 or y_var == 0.0:
        return 0.0
    cov = sum((a - x_mu) * (b - y_mu) for a, b in zip(x, y))
    return cov / math.sqrt(x_var * y_var)


def _rank(values: list[float]) -> list[float]:
    if not values:
        return []
    order = sorted(range(len(values)), key=lambda idx: values[idx])
    ranks = [0.0] * len(values)
    for rank_idx, original_idx in enumerate(order, start=1):
        ranks[original_idx] = float(rank_idx)
    return ranks


def _spearman(x: list[float], y: list[float]) -> float:
    return _pearson(_rank(x), _rank(y))


def _normalize_weights(weights: dict[str, float]) -> dict[str, float]:
    if not weights:
        return {}
    total = sum(abs(value) for value in weights.values())
    if total == 0.0:
        equal = 1.0 / len(weights)
        return {name: equal for name in weights}
    return {name: value / total for name, value in weights.items()}


def _forward_returns(prices: list[float], horizon: int) -> list[float]:
    if horizon <= 0 or len(prices) <= horizon:
        return []
    return [
        (prices[idx + horizon] - prices[idx]) / max(abs(prices[idx]), 1e-12)
        for idx in range(len(prices) - horizon)
    ]


def _truncate_pair(x: list[float], y: list[float]) -> tuple[list[float], list[float]]:
    length = min(len(x), len(y))
    return x[:length], y[:length]


def _matrix_vector(matrix: list[list[float]], vector: list[float]) -> list[float]:
    return [sum(item * weight for item, weight in zip(row, vector)) for row in matrix]


def _power_iteration(covariance: list[list[float]], steps: int = 50) -> list[float]:
    if not covariance:
        return []
    vector = [1.0 / len(covariance) for _ in covariance]
    for _ in range(steps):
        nxt = _matrix_vector(covariance, vector)
        norm = math.sqrt(sum(value * value for value in nxt))
        if norm == 0.0:
            break
        vector = [value / norm for value in nxt]
    return vector


class SignalFactory:
    """Small helper set for generating simple research signals in Python."""

    @staticmethod
    def momentum(prices: list[float], lookback: int = 20) -> list[float]:
        if len(prices) <= lookback:
            return [0.0 for _ in prices]
        signals = [0.0] * len(prices)
        for idx in range(lookback, len(prices)):
            base = max(abs(prices[idx - lookback]), 1e-12)
            signals[idx] = (prices[idx] - prices[idx - lookback]) / base
        return _winsorize(_zscore(signals))

    @staticmethod
    def mean_reversion(prices: list[float], lookback: int = 20) -> list[float]:
        if len(prices) <= lookback:
            return [0.0 for _ in prices]
        signals = [0.0] * len(prices)
        for idx in range(lookback, len(prices)):
            window = prices[idx - lookback:idx]
            sigma = _safe_std(window)
            mu = _safe_mean(window)
            if sigma > 0.0:
                signals[idx] = -(prices[idx] - mu) / sigma
        return _winsorize(signals)

    @staticmethod
    def sentiment(sentiment_series: list[float], smooth: int = 5) -> list[float]:
        if not sentiment_series:
            return []
        scores: list[float] = []
        for idx in range(len(sentiment_series)):
            start = max(0, idx - smooth + 1)
            scores.append(_safe_mean(sentiment_series[start:idx + 1]))
        return _winsorize(scores)

    @staticmethod
    def statistical_arbitrage(spread_series: list[float], lookback: int = 20) -> list[float]:
        if len(spread_series) <= lookback:
            return [0.0 for _ in spread_series]
        scores = [0.0] * len(spread_series)
        for idx in range(lookback, len(spread_series)):
            window = spread_series[idx - lookback:idx]
            sigma = _safe_std(window)
            mu = _safe_mean(window)
            if sigma > 0.0:
                scores[idx] = -(spread_series[idx] - mu) / sigma
        return _winsorize(scores)


class AlphaCombiner:
    """Combines alpha signals and computes research diagnostics."""

    @staticmethod
    def information_coefficient(signal: list[float], forward_returns: list[float], rank: bool = True) -> float:
        signal, forward_returns = _truncate_pair(signal, forward_returns)
        if rank:
            return _spearman(signal, forward_returns)
        return _pearson(signal, forward_returns)

    @classmethod
    def ic_by_signal(
        cls,
        signal_map: dict[str, list[float]],
        forward_returns: list[float],
        rank: bool = True,
    ) -> dict[str, float]:
        return {
            name: cls.information_coefficient(series, forward_returns, rank=rank)
            for name, series in signal_map.items()
        }

    @classmethod
    def alpha_decay(
        cls,
        signal: list[float],
        prices: list[float],
        horizons: Iterable[int] = (1, 3, 5, 10, 21),
    ) -> dict[int, float]:
        decay: dict[int, float] = {}
        for horizon in horizons:
            fwd = _forward_returns(prices, horizon)
            aligned_signal = signal[: len(fwd)]
            decay[horizon] = cls.information_coefficient(aligned_signal, fwd, rank=True)
        return decay

    @staticmethod
    def signal_correlations(signal_map: dict[str, list[float]]) -> dict[str, dict[str, float]]:
        names = list(signal_map)
        matrix: dict[str, dict[str, float]] = {}
        for left in names:
            row: dict[str, float] = {}
            for right in names:
                x, y = _truncate_pair(signal_map[left], signal_map[right])
                row[right] = _pearson(x, y)
            matrix[left] = row
        return matrix

    @classmethod
    def optimal_weights(
        cls,
        signal_map: dict[str, list[float]],
        forward_returns: list[float],
        method: str = "ic",
    ) -> dict[str, float]:
        if not signal_map:
            return {}
        ics = cls.ic_by_signal(signal_map, forward_returns)
        correlations = cls.signal_correlations(signal_map)
        raw: dict[str, float] = {}
        for name in signal_map:
            avg_corr = _safe_mean(
                abs(value)
                for other, value in correlations[name].items()
                if other != name
            )
            diversification = 1.0 / max(1.0 + avg_corr, PHI_INV)
            base_ic = abs(ics.get(name, 0.0)) + PHI_INV_3
            if method == "risk_adjusted":
                volatility = _safe_std(signal_map[name])
                raw[name] = math.copysign(base_ic * diversification / max(volatility, PHI_INV_3), ics.get(name, 0.0))
            elif method == "phi":
                raw[name] = math.copysign((base_ic ** PHI_INV) * diversification, ics.get(name, 0.0))
            else:
                raw[name] = math.copysign(base_ic * diversification, ics.get(name, 0.0))
        return _normalize_weights(raw)

    @classmethod
    def aggregate(
        cls,
        signal_map: dict[str, list[float]],
        prices: list[float],
        method: str = "ic",
    ) -> AlphaCombinationResult:
        if not signal_map:
            return AlphaCombinationResult([], {}, {}, {}, {})
        forward_returns = _forward_returns(prices, 1)
        weights = cls.optimal_weights(signal_map, forward_returns, method=method)
        max_len = min(len(series) for series in signal_map.values())
        combined = [0.0] * max_len
        for name, series in signal_map.items():
            weight = weights.get(name, 0.0)
            for idx, value in enumerate(series[:max_len]):
                combined[idx] += weight * value
        decay = cls.alpha_decay(combined, prices)
        return AlphaCombinationResult(
            combined_signal=_winsorize(combined),
            weights=weights,
            information_coefficients=cls.ic_by_signal(signal_map, forward_returns),
            decay_by_horizon=decay,
            correlation_matrix=cls.signal_correlations(signal_map),
        )


class FactorConstructor:
    """Builds style, macro, statistical, and alternative factors."""

    @staticmethod
    def style_factors(items: list[FactorInput]) -> dict[str, dict[str, float]]:
        if not items:
            return {"value": {}, "momentum": {}, "quality": {}}
        value_raw = {
            item.asset: item.earnings_yield + item.free_cash_flow_yield - item.price_to_book * PHI_INV_3
            for item in items
        }
        momentum_raw = {
            item.asset: 0.5 * item.return_21d + 0.3 * item.return_63d + 0.2 * item.return_126d
            for item in items
        }
        quality_raw = {
            item.asset: item.return_on_equity + item.gross_margin - item.leverage * PHI_INV_2
            for item in items
        }
        return {
            "value": FactorConstructor._cross_sectional_standardize(value_raw),
            "momentum": FactorConstructor._cross_sectional_standardize(momentum_raw),
            "quality": FactorConstructor._cross_sectional_standardize(quality_raw),
        }

    @staticmethod
    def macro_factors(items: list[FactorInput]) -> dict[str, dict[str, float]]:
        return {
            "macro": FactorConstructor._cross_sectional_standardize(
                {
                    item.asset: item.macro_beta + PHI_INV_2 * item.inflation_sensitivity - PHI_INV_3 * item.yield_curve_sensitivity
                    for item in items
                }
            )
        }

    @staticmethod
    def alternative_data_factors(items: list[FactorInput]) -> dict[str, dict[str, float]]:
        return {
            "alternative": FactorConstructor._cross_sectional_standardize(
                {
                    item.asset: item.alt_data_score + 0.5 * item.web_traffic_score + 0.5 * item.sentiment_score
                    for item in items
                }
            )
        }

    @staticmethod
    def pca_factor(items: list[FactorInput]) -> dict[str, float]:
        if not items:
            return {}
        features = [
            [
                item.earnings_yield,
                item.free_cash_flow_yield,
                item.return_21d,
                item.return_on_equity,
                item.macro_beta,
                item.alt_data_score,
            ]
            for item in items
        ]
        standardized = FactorConstructor._column_standardize(features)
        covariance = FactorConstructor._covariance_matrix(standardized)
        eigenvector = _power_iteration(covariance)
        scores = {
            item.asset: sum(value * weight for value, weight in zip(row, eigenvector))
            for item, row in zip(items, standardized)
        }
        return FactorConstructor._cross_sectional_standardize(scores)

    @staticmethod
    def _cross_sectional_standardize(values: dict[str, float]) -> dict[str, float]:
        if not values:
            return {}
        raw = list(values.values())
        sigma = _safe_std(raw)
        mu = _safe_mean(raw)
        if sigma == 0.0:
            return {asset: 0.0 for asset in values}
        return {asset: (value - mu) / sigma for asset, value in values.items()}

    @staticmethod
    def _column_standardize(matrix: list[list[float]]) -> list[list[float]]:
        if not matrix:
            return []
        columns = list(zip(*matrix))
        mus = [_safe_mean(column) for column in columns]
        sigmas = [_safe_std(column) for column in columns]
        output: list[list[float]] = []
        for row in matrix:
            output.append([
                0.0 if sigma == 0.0 else (value - mu) / sigma
                for value, mu, sigma in zip(row, mus, sigmas)
            ])
        return output

    @staticmethod
    def _covariance_matrix(matrix: list[list[float]]) -> list[list[float]]:
        if not matrix:
            return []
        columns = list(zip(*matrix))
        output: list[list[float]] = []
        for left in columns:
            row: list[float] = []
            for right in columns:
                row.append(_pearson(list(left), list(right)))
            output.append(row)
        return output


class Backtester:
    """Simple cross-sectional long-short backtester."""

    @staticmethod
    def _weights_from_scores(scores: dict[str, float]) -> dict[str, float]:
        if not scores:
            return {}
        winsorized = {asset: max(-3.0, min(3.0, value)) for asset, value in scores.items()}
        total = sum(abs(value) for value in winsorized.values())
        if total == 0.0:
            equal = 1.0 / len(winsorized)
            return {asset: equal for asset in winsorized}
        return {asset: value / total for asset, value in winsorized.items()}

    @classmethod
    def run(
        cls,
        prices_by_asset: dict[str, list[float]],
        signal_by_asset: dict[str, list[float]],
        transaction_cost_bps: float = 5.0,
    ) -> BacktestResult:
        assets = sorted(set(prices_by_asset) & set(signal_by_asset))
        if not assets:
            return BacktestResult([], [1.0], [], [], 0.0, 0.0, 0.0, 0.0)
        horizon = min(len(prices_by_asset[asset]) - 1 for asset in assets)
        horizon = min(horizon, min(len(signal_by_asset[asset]) for asset in assets) - 1)
        if horizon <= 0:
            return BacktestResult([], [1.0], [], [], 0.0, 0.0, 0.0, 0.0)

        equity = [1.0]
        returns: list[float] = []
        turnover: list[float] = []
        positions: list[dict[str, float]] = []
        previous_weights = {asset: 0.0 for asset in assets}

        for idx in range(horizon):
            score_slice = {asset: signal_by_asset[asset][idx] for asset in assets}
            weights = cls._weights_from_scores(score_slice)
            gross_return = 0.0
            for asset, weight in weights.items():
                price_now = prices_by_asset[asset][idx]
                price_next = prices_by_asset[asset][idx + 1]
                asset_return = (price_next - price_now) / max(abs(price_now), 1e-12)
                gross_return += weight * asset_return
            rebalance = 0.5 * sum(abs(weights[asset] - previous_weights.get(asset, 0.0)) for asset in assets)
            net_return = gross_return - rebalance * (transaction_cost_bps / 10_000.0)
            returns.append(net_return)
            turnover.append(rebalance)
            positions.append(weights)
            equity.append(equity[-1] * (1.0 + net_return))
            previous_weights = weights

        sharpe = cls._annualized_sharpe(returns)
        cumulative_return = equity[-1] - 1.0
        max_drawdown = cls._max_drawdown(equity)
        hit_rate = sum(1 for value in returns if value > 0.0) / len(returns) if returns else 0.0
        return BacktestResult(returns, equity, turnover, positions, sharpe, cumulative_return, max_drawdown, hit_rate)

    @staticmethod
    def _annualized_sharpe(returns: list[float], periods_per_year: int = 252) -> float:
        sigma = _safe_std(returns)
        if sigma == 0.0:
            return 0.0
        return math.sqrt(periods_per_year) * _safe_mean(returns) / sigma

    @staticmethod
    def _max_drawdown(equity_curve: list[float]) -> float:
        if not equity_curve:
            return 0.0
        peak = equity_curve[0]
        drawdown = 0.0
        for value in equity_curve:
            peak = max(peak, value)
            drawdown = min(drawdown, value / max(peak, 1e-12) - 1.0)
        return abs(drawdown)


class AlphaResearch:
    """Performance attribution and robustness analysis."""

    @staticmethod
    def performance_attribution(
        portfolio_returns: list[float],
        factor_returns: dict[str, list[float]],
    ) -> dict[str, float]:
        attribution: dict[str, float] = {}
        for name, series in factor_returns.items():
            aligned_factor, aligned_portfolio = _truncate_pair(series, portfolio_returns)
            beta = _pearson(aligned_factor, aligned_portfolio)
            attribution[name] = beta * _safe_mean(aligned_factor)
        return attribution

    @staticmethod
    def factor_turnover(weight_history: list[dict[str, float]]) -> tuple[float, float]:
        if len(weight_history) < 2:
            return 0.0, 0.0
        turnovers: list[float] = []
        for prev, curr in zip(weight_history, weight_history[1:]):
            assets = set(prev) | set(curr)
            turnovers.append(0.5 * sum(abs(curr.get(asset, 0.0) - prev.get(asset, 0.0)) for asset in assets))
        return _safe_mean(turnovers), max(turnovers, default=0.0)

    @staticmethod
    def robustness_test(
        signal: list[float],
        forward_returns: list[float],
        bootstrap_rounds: int = 100,
        seed: int = 13,
    ) -> tuple[float, float]:
        signal, forward_returns = _truncate_pair(signal, forward_returns)
        if not signal:
            return 0.0, 0.0
        rng = random.Random(seed)
        sampled_ics: list[float] = []
        for _ in range(bootstrap_rounds):
            sample_idx = [rng.randrange(len(signal)) for _ in range(len(signal))]
            sampled_signal = [signal[idx] for idx in sample_idx]
            sampled_returns = [forward_returns[idx] for idx in sample_idx]
            sampled_ics.append(AlphaCombiner.information_coefficient(sampled_signal, sampled_returns, rank=True))
        hit_rate = sum(1 for value in sampled_ics if value > 0.0) / len(sampled_ics)
        return _safe_mean(sampled_ics), hit_rate

    @staticmethod
    def out_of_sample_validation(
        train_signal: list[float],
        train_returns: list[float],
        test_signal: list[float],
        test_returns: list[float],
    ) -> tuple[float, float]:
        train_ic = AlphaCombiner.information_coefficient(train_signal, train_returns, rank=True)
        test_ic = AlphaCombiner.information_coefficient(test_signal, test_returns, rank=True)
        return train_ic, test_ic

    @classmethod
    def full_report(
        cls,
        combination: AlphaCombinationResult,
        backtest: BacktestResult,
        prices: list[float],
        factor_returns: Optional[dict[str, list[float]]] = None,
    ) -> ResearchReport:
        factor_returns = factor_returns or {}
        fwd = _forward_returns(prices, 1)
        robust_mean, robust_hit = cls.robustness_test(combination.combined_signal[: len(fwd)], fwd)
        turnover_mean, turnover_max = cls.factor_turnover(backtest.positions)
        split = max(1, len(fwd) // 2)
        train_ic, test_ic = cls.out_of_sample_validation(
            combination.combined_signal[:split],
            fwd[:split],
            combination.combined_signal[split: len(fwd)],
            fwd[split:],
        )
        return ResearchReport(
            attribution=cls.performance_attribution(backtest.portfolio_returns, factor_returns),
            turnover_mean=turnover_mean,
            turnover_max=turnover_max,
            robustness_mean_ic=robust_mean,
            robustness_hit_rate=robust_hit,
            train_ic=train_ic,
            test_ic=test_ic,
            decay_by_horizon=combination.decay_by_horizon,
        )


class AlphaPipeline:
    """End-to-end alpha research pipeline with backtesting integration."""

    def __init__(self) -> None:
        self.combiner = AlphaCombiner()
        self.research = AlphaResearch()

    def run(
        self,
        prices_by_asset: dict[str, list[float]],
        signal_library: dict[str, dict[str, list[float]]],
        factor_returns: Optional[dict[str, list[float]]] = None,
        combination_method: str = "ic",
    ) -> tuple[AlphaCombinationResult, BacktestResult, ResearchReport]:
        if not prices_by_asset or not signal_library:
            empty_combo = AlphaCombinationResult([], {}, {}, {}, {})
            empty_backtest = BacktestResult([], [1.0], [], [], 0.0, 0.0, 0.0, 0.0)
            empty_report = ResearchReport({}, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, {})
            return empty_combo, empty_backtest, empty_report

        primary_asset = next(iter(prices_by_asset))
        combo = self.combiner.aggregate(signal_library[primary_asset], prices_by_asset[primary_asset], method=combination_method)

        combined_by_asset: dict[str, list[float]] = {}
        for asset, signals in signal_library.items():
            asset_combo = self.combiner.aggregate(signals, prices_by_asset[asset], method=combination_method)
            combined_by_asset[asset] = asset_combo.combined_signal

        backtest = Backtester.run(prices_by_asset, combined_by_asset)
        report = self.research.full_report(combo, backtest, prices_by_asset[primary_asset], factor_returns=factor_returns)
        return combo, backtest, report


__all__ = [
    "PriceBar",
    "Signal",
    "FactorInput",
    "AlphaCombinationResult",
    "BacktestResult",
    "ResearchReport",
    "SignalFactory",
    "AlphaCombiner",
    "FactorConstructor",
    "Backtester",
    "AlphaResearch",
    "AlphaPipeline",
]
