const now=()=>new Date().toISOString();
const cls=['repo_sentinel','build_runner','research_worker','security_monitor','receipt_writer','vault_operator','docs_publisher','release_gatekeeper'];
const disabled=['secret_exfiltration','raw_private_key_storage','live_broker_execution','live_money_movement','token_sale','public_mainnet_bridge','unauthorized_cloudflare_mutation'];
const h=v=>{let x=2166136261;for(const c of JSON.stringify(v))x=Math.imul(x^c.charCodeAt(0),16777619);return `px_${(x>>>0).toString(16)}`};
const state={brains:[],receipts:[]};
const j=(b,s=200)=>new Response(JSON.stringify(b,null,2),{status:s,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-api-key'}});
const html=()=>new Response(`<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>PARALLAX Brain Fleet</title><style>body{margin:0;background:#050816;color:#e5f7ff;font-family:Inter,system-ui}main{max-width:1180px;margin:auto;padding:38px}section{background:linear-gradient(135deg,#07111f,#111827);border:1px solid #1e3a5f;border-radius:24px;padding:24px;margin:18px 0;box-shadow:0 20px 80px #0008}.hero{background:radial-gradient(circle at 15% 20%,#22d3ee55,transparent 35%),radial-gradient(circle at 80% 10%,#a78bfa44,transparent 35%),#050816}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px}.card{border:1px solid #334155;border-radius:16px;padding:16px;background:#020617}.badge{display:inline-block;margin:4px;padding:6px 10px;border-radius:999px;background:#0f766e;color:white}button,input,textarea{border-radius:10px;border:1px solid #334155;background:#020617;color:#e5f7ff;padding:10px}button{background:#0891b2;cursor:pointer}pre{white-space:pre-wrap}</style></head><body><main><section class=hero><h1>PARALLAX Cloudflare Brain Fleet</h1><p>Edge-agent control plane for repo sentinels, builders, research workers, security monitors, vault operators, release gates, and receipt writers.</p><span class=badge>paper/testnet first</span><span class=badge>Durable Object ready</span><span class=badge>Workers AI ready</span><span class=badge>MCP gated</span></section><section><h2>Brain classes</h2><div class=grid>${cls.map(c=>`<div class=card><b>${c}</b><p>Governed agent Worker lane.</p></div>`).join('')}</div></section><section><h2>Talk to the fleet</h2><textarea id=m rows=4 style="width:100%">Plan status for PARALLAX vault runtime</textarea><br><button onclick="send()">Send message</button><button onclick="spawn()">Spawn sample brain</button><button onclick="tick()">Tick fleet</button><pre id=o>Ready.</pre></section></main><script>async function call(p,b){let r=await fetch(p,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b||{})});o.textContent=JSON.stringify(await r.json(),null,2)}function send(){call('/api/brain-fleet/message',{message:m.value})}function spawn(){call('/api/brain-fleet/spawn',{class:'repo_sentinel',repo:'PARALLAX-Exchange-Clearinghouse'})}function tick(){call('/api/brain-fleet/tick',{reason:'operator_tick'})}</script></body></html>`,{headers:{'content-type':'text/html;charset=utf-8'}});
async function body(r){try{return await r.json()}catch{return{}}}
function rec(t,p){const r={receiptId:h({t,p,n:state.receipts.length}),type:t,payloadHash:h(p),createdAt:now(),boundary:'paper_testnet_agent_fleet'};state.receipts.push(r);return r}
function deny(cap){return j({error:'brain_fleet_boundary_denied',capability:cap,disabled,posture:'paper_testnet_first'},403)}
function bad(p){return /secret|private[-_]?key|live[-_]?broker|live[-_]?money|token[-_]?sale|mainnet[-_]?bridge|cloudflare\/execute/i.test(p)}
async function route(req){const u=new URL(req.url),p=u.pathname;if(req.method==='OPTIONS')return j({ok:true});if(bad(p))return deny(p);if(p==='/'||p==='/brain-fleet')return html();if(p==='/api/brain-fleet')return j({platform:'PARALLAX Cloudflare Brain Fleet',posture:'paper_testnet_first',brainClasses:cls,brains:state.brains,receipts:state.receipts.length});if(p==='/api/brain-fleet/receipts')return j({receipts:state.receipts});if(p==='/api/brain-fleet/spawn'&&req.method==='POST'){const b=await body(req),brain={brainId:`pxbrain_${h(b).slice(3)}`,class:cls.includes(b.class)?b.class:'repo_sentinel',repo:b.repo||'unscoped',authority:'plan_and_receipt_only',status:'ready',createdAt:now()};state.brains.push(brain);return j({brain,receipt:rec('brain.spawned',brain)},201)}if(p==='/api/brain-fleet/message'&&req.method==='POST'){const b=await body(req),answer={accepted:true,message:b.message||'',plan:['classify request','check boundaries','propose action','write receipt'],execution:'not_autonomous_mutation'};return j({answer,receipt:rec('brain.message.accepted',answer)})}if(p==='/api/brain-fleet/tick'&&req.method==='POST'){for(const x of state.brains)x.lastTick=now();return j({brains:state.brains,receipt:rec('brain.tick.completed',{count:state.brains.length})})}return j({error:'not_found',path:p},404)}
export{route,state};export default{fetch:route};
