interface Env {
  PARALLAX_ENV: string;
  PARALLAX_PUBLIC_POSTURE: string;
  PARALLAX_CORE_URL: string;
  PARALLAX_TUNNEL_EXPECTED_HOST: string;
  PARALLAX_ALLOWED_ORIGINS: string;
  PARALLAX_REQUIRE_AUTH_FOR_MUTATION: string;
  PARALLAX_EDGE_TOKEN?: string;
}
