const now=()=>new Date().toISOString();
const hash=(v)=>{let h=2166136261;for(const c of JSON.stringify(v))h=Math.imul(h^c.charCodeAt(0),16777619);return `px_${(h>>>0).toString(16).padStart(8,'0')}`};
const day=()=>now().slice(0,10);
const seed=()=>({schema:'parallax.canonical_vault_state.v1',version:1,updatedAt:now(),ledgers:[{id:'parallax-paper-ledger',mode:'paper',assets:['PXUSD','PXAI','PXCRED'],live:false},{id:'agent-credit-ledger',mode:'paper',assets:['PXCRED','PXGPU'],live:false},{id:'icp-local-ledger',mode:'testnet',assets:['PXICP'],live:false}],wallets:[],vaults:[],agents:[{id:'agent-market-sentinel',status:'running',cadence:'simulated-30s'},{id:'agent-risk-gatekeeper',status:'idle',cadence:'on-demand'},{id:'agent-receipt-writer',status:'running',cadence:'event-driven'},{id:'agent-ledger-reconciler',status:'running',cadence:'simulated-60s'},{id:'agent-connector-health',status:'running',cadence:'simulated-120s'},{id:'agent-billing-meter',status:'idle',cadence:'event-driven'}],principals:[{principalId:'demo-operator',apiKey:'pk_demo_operator',roles:['vault.admin'],vaultIds:['*'],dailyLimitPXUSD:25000,requiresHumanAbovePXUSD:1000,spentByDay:{}}],receipts:[],receiptHead:'GENESIS'});
function mkMemoryStore(initial=seed()){let s=initial;return{kind:'memory',async load(){return s},async save(n){s={...n,version:(s.version||0)+1,updatedAt:now()};return s}}}
function mkKvStore(kv,key='parallax:vault-state'){return{kind:'cloudflare-kv',async load(){const raw=await kv.get(key);return raw?JSON.parse(raw):seed()},async save(n){n={...n,version:(n.version||0)+1,updatedAt:now()};await kv.put(key,JSON.stringify(n));return n}}}
function auth(request,state){const key=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'')||request.headers.get('x-api-key')||'pk_demo_operator';const principal=state.principals.find(p=>p.apiKey===key);return principal?{ok:true,principal}:{ok:false,error:'unauthorized_principal'}}
function canSpend(principal,amount){const d=day();const spent=principal.spentByDay[d]||0;if(spent+amount>principal.dailyLimitPXUSD)return{ok:false,error:'daily_limit_exceeded',spent,limit:principal.dailyLimitPXUSD};if(amount>principal.requiresHumanAbovePXUSD)return{ok:false,error:'human_approval_required',amount,threshold:principal.requiresHumanAbovePXUSD};principal.spentByDay[d]=spent+amount;return{ok:true,spent:principal.spentByDay[d]}}
function receipt(state,type,payload,principalId='system'){const prev=state.receiptHead||'GENESIS';const r={receiptId:hash({type,payload,prev,n:state.receipts.length}),type,payloadHash:hash(payload),prevReceiptHash:prev,receiptHash:hash({type,payload,prev}),principalId,createdAt:now(),boundary:'paper_testnet_only'};state.receipts.push(r);state.receiptHead=r.receiptHash;return r}
function snapshot(state){return{schema:'parallax.vault_recovery_snapshot.v1',version:state.version,updatedAt:state.updatedAt,counts:{vaults:state.vaults.length,wallets:state.wallets.length,receipts:state.receipts.length},receiptHead:state.receiptHead,recoveryHash:hash(state)}}
function recover(state,expected){const snap=snapshot(state);return{ok:!expected||snap.recoveryHash===expected,snapshot:snap}}
export{auth,canSpend,hash,mkKvStore,mkMemoryStore,receipt,recover,seed,snapshot};