import{auth,canSpend,hash,mkKvStore,mkMemoryStore,receipt,recover,snapshot}from'./vault-state.js';
import{BROKERS,denyLive,makeSecretHandle,makeBrokerConnector,makeInternalTokenRail}from'./regulated-live.js';
const now=()=>new Date().toISOString();const memory=mkMemoryStore();
const BOUNDARIES=['no custody','no private keys','no live broker execution','no live money movement','no token sale','no public mainnet bridge','paper/testnet only'];
const DISABLED=['custody','private_key_import','seed_phrase_capture','live_broker_order','live_money_transfer','token_sale','yield_claim','redemption_claim','public_mainnet_bridge'];
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-api-key'}});
const blocked=(capability)=>json({error:'boundary_blocked',capability,posture:'paper_testnet_only',boundaries:BOUNDARIES},403);
const readJson=async(request)=>{try{return await request.json()}catch{return{}}};
const storeFor=(env={})=>env.PARALLAX_VAULT_STATE?mkKvStore(env.PARALLAX_VAULT_STATE):memory;
const mkWallet=(body={})=>({walletId:`pxw_${hash(body).slice(3)}`,agentId:body.agentId||'external-agent',owner:body.owner||'external-owner',mode:'paper',balances:{PXUSD:Number(body.pxusd??10000),PXAI:Number(body.pxai??1000),PXCRED:0},connectors:body.connectors||[],limits:{dailyPXUSD:Number(body.dailyPXUSD??5000),requiresHumanAbove:Number(body.requiresHumanAbove??1000)},createdAt:now()});
const mkVault=(body={})=>{const vaultId=`pxv_${hash({body,at:now()}).slice(3)}`;const wallet=mkWallet({agentId:body.agentId||'vault-agent',owner:body.owner||'vault-owner',pxusd:body.pxusd??50000,pxai:body.pxai??10000,connectors:['evm','solana','icp','bitcoin','cosmos']});return{vaultId,name:body.name||'Agent Swarm Vault',owner:body.owner||'vault-owner',mode:'paper',status:'active_sample',walletSystem:{primaryWallet:wallet,wallets:[wallet],outsideConnectors:[{id:'evm',status:'ready_to_connect',networks:['ethereum','base','polygon']},{id:'solana',status:'ready_to_connect',networks:['solana']},{id:'icp',status:'ready_to_connect',networks:['icp-local','icp-testnet']},{id:'bitcoin',status:'watch_only_ready',networks:['bitcoin']},{id:'cosmos',status:'ready_to_connect',networks:['cosmos','osmosis']}],policy:{agentAllowlist:[body.agentId||'vault-agent','agent-risk-gatekeeper','agent-receipt-writer'],humanThresholdPXUSD:1000,liveExecution:false,custody:false}},prebuilt:{tools:['policy-pack-alpha','receipt-room','ledger-reconciler','market-sentinel','billing-meter','connector-health'],ledgers:['parallax-paper-ledger','agent-credit-ledger','icp-local-ledger'],permissions:['read_balances','propose_transfer','request_receipt','tick_agent'],sampleApiKey:`pk_demo_${hash(vaultId).slice(3)}`},regulatedLive:{status:'disabled',secretHandles:[],brokerConnectors:[],internalTokenRails:[]},monetization:{plan:body.plan||'vault_api_subscription',metered:true,units:['vault/month','api_call','receipt','connector']},createdAt:now()}};
async function withState(request,env,fn){const store=storeFor(env);const state=await store.load();state.secretHandles??=[];state.brokerConnectors??=[];state.internalTokenRails??=[];if(!state.vaults.length){const vault=mkVault({name:'Demo Agent Swarm Vault',owner:'demo-operator',agentId:'external-demo-agent'});state.vaults.push(vault);state.wallets.push(vault.walletSystem.primaryWallet)}const a=auth(request,state);if(!a.ok)return json({error:a.error},401);const result=await fn(state,a.principal);await store.save(state);return result}
const boundaryResponse=()=>json({posture:'paper_testnet_only',readyForUse:true,boundaries:BOUNDARIES,disabledCapabilities:DISABLED,allowedCapabilities:['create_agent_vault','create_paper_wallet','link_outside_wallet_reference','register_secret_reference','register_broker_connector','register_internal_token_rail','simulate_paper_transfer','tick_background_agent','write_receipt','read_snapshot','verify_recovery'],marketingSafeClaim:'PARALLAX provides paper/testnet agent vaults and receipt evidence for external AI agents without custody, private keys, live brokerage, live money movement, token sales, or public mainnet bridge execution.'});
function isForbiddenPath(path){return /custody|private[-_]?key|seed|live[-_]?broker|broker\/order|live[-_]?money|token[-_]?sale|yield|redeem|mainnet[-_]?bridge/i.test(path)}
async function route(request,env={}){const url=new URL(request.url);const path=url.pathname;if(request.method==='OPTIONS')return json({ok:true});if(path==='/api/regulated-live')return json({posture:'regulated_live_disabled_until_approved',brokers:BROKERS,capabilities:['secret_reference_registration','broker_connector_registration','internal_token_rail_registration','sandbox_order_proposal'],disabled:['raw_secret_storage','private_key_storage','live_order_submit','live_money_transfer','token_sale','public_mainnet_bridge']});if(path==='/api/live/execute'||path==='/api/live-money/transfer'||path==='/api/token-sale')return json(denyLive(path),403);if(isForbiddenPath(path))return blocked(path);if(path==='/api/boundaries')return boundaryResponse();
 if(path==='/api/status')return withState(request,env,async(s)=>json({ok:true,platform:'PARALLAX Agent Vault API',posture:'paper_testnet_first',regulatedLive:'disabled_until_approved',stateStore:storeFor(env).kind,persistence:storeFor(env).kind==='cloudflare-kv'?'durable_kv':'memory_fallback',receiptHead:s.receiptHead,servers:['agent-control','vault-wallet-ledger','proof-room','billing-meter'],boundaries:BOUNDARIES,disabledCapabilities:DISABLED}));
 if(path==='/api/recovery')return withState(request,env,async(s)=>json(recover(s,url.searchParams.get('hash'))));
 if(path==='/api/snapshot')return withState(request,env,async(s)=>json(snapshot(s)));
 if(path==='/api/secrets'&&request.method==='GET')return withState(request,env,async(s)=>json({secretHandles:s.secretHandles||[],storesSecretValues:false}));
 if(path==='/api/secrets'&&request.method==='POST')return withState(request,env,async(s,p)=>{const handle=makeSecretHandle(await readJson(request));s.secretHandles.push(handle);return json({secretHandle:handle,receipt:receipt(s,'secret.reference.registered',handle,p.principalId)},201)});
 if(path==='/api/brokers'&&request.method==='GET')return withState(request,env,async(s)=>json({brokerConnectors:s.brokerConnectors||[],supported:BROKERS,liveExecution:false}));
 if(path==='/api/brokers'&&request.method==='POST')return withState(request,env,async(s,p)=>{const connector=makeBrokerConnector(await readJson(request));s.brokerConnectors.push(connector);return json({brokerConnector:connector,receipt:receipt(s,'broker.connector.registered',connector,p.principalId)},201)});
 if(path==='/api/brokers/execute'&&request.method==='POST')return json(denyLive('live_broker_execution',{sandboxRoute:'POST /api/brokers/paper-order'}),403);
 if(path==='/api/brokers/paper-order'&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const proposal={paperOrderId:`pxpo_${hash(body).slice(3)}`,broker:body.broker||'alpaca_sandbox',symbol:body.symbol||'PXUSD.PAPER',side:body.side||'buy',quantity:Number(body.quantity||1),mode:'paper_or_sandbox',liveExecution:false,createdAt:now()};return json({paperOrder:proposal,receipt:receipt(s,'broker.paper_order.proposed',proposal,p.principalId)},201)});
 if(path==='/api/token-rails'&&request.method==='GET')return withState(request,env,async(s)=>json({internalTokenRails:s.internalTokenRails||[],liveRedeemability:false}));
 if(path==='/api/token-rails'&&request.method==='POST')return withState(request,env,async(s,p)=>{const rail=makeInternalTokenRail(await readJson(request));s.internalTokenRails.push(rail);return json({internalTokenRail:rail,receipt:receipt(s,'internal_token_rail.registered',rail,p.principalId)},201)});
 if(path==='/api/token-rails/live-transfer'&&request.method==='POST')return json(denyLive('live_money_movement_through_internal_tokens',{safeRoute:'POST /api/vaults/:id/ledger/transfer'}),403);
 if(path==='/api/monetization')return json({paths:['vault_api_subscription','agent_wallet_metering','receipt_room_enterprise','connector_marketplace','managed_agent_ops','white_label_vaults','regulated_live_readiness_package'],boundary:'pricing_not_set_in_code',forbidden:['token_sale','yield_claim','redemption_claim']});
 if(path==='/api/agents'&&request.method==='GET')return withState(request,env,async(s)=>json({agents:s.agents}));
 if(path==='/api/agents/tick'&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const agent=s.agents.find(a=>a.id===body.agentId)||s.agents[0];agent.status='running';agent.lastTick=now();return json({agent,receipt:receipt(s,'agent.tick',agent,p.principalId)})});
 if(path==='/api/ledgers'&&request.method==='GET')return withState(request,env,async(s)=>json({ledgers:s.ledgers}));
 if(path==='/api/wallets'&&request.method==='GET')return withState(request,env,async(s)=>json({wallets:s.wallets}));
 if(path==='/api/wallets'&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const wallet=mkWallet(body);s.wallets.push(wallet);return json({wallet,receipt:receipt(s,'wallet.created',wallet,p.principalId),upgradePath:'POST /api/vaults creates a full vault around the wallet system'},201)});
 if(path==='/api/vaults'&&request.method==='GET')return withState(request,env,async(s)=>json({vaults:s.vaults}));
 if(path==='/api/vaults'&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const vault=mkVault(body);s.vaults.push(vault);s.wallets.push(vault.walletSystem.primaryWallet);return json({vault,apiKey:vault.prebuilt.sampleApiKey,receipt:receipt(s,'vault.created',vault,p.principalId)},201)});
 const vaultMatch=path.match(/^\/api\/vaults\/([^/]+)$/);if(vaultMatch&&request.method==='GET')return withState(request,env,async(s)=>{const vault=s.vaults.find(v=>v.vaultId===vaultMatch[1]);return vault?json({vault}):json({error:'vault_not_found'},404)});
 const connMatch=path.match(/^\/api\/vaults\/([^/]+)\/connectors$/);if(connMatch&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const vault=s.vaults.find(v=>v.vaultId===connMatch[1]);if(!vault)return json({error:'vault_not_found'},404);const connector={id:body.id||'custom_connector',status:'linked_sample',networks:body.networks||['paper']};vault.walletSystem.outsideConnectors.push(connector);return json({connector,receipt:receipt(s,'vault.connector.linked',{vaultId:vault.vaultId,connector},p.principalId)})});
 const agentMatch=path.match(/^\/api\/vaults\/([^/]+)\/agents$/);if(agentMatch&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const vault=s.vaults.find(v=>v.vaultId===agentMatch[1]);if(!vault)return json({error:'vault_not_found'},404);const agentId=body.agentId||`agent-${hash(body).slice(3)}`;vault.walletSystem.policy.agentAllowlist.push(agentId);return json({agentId,allowlist:vault.walletSystem.policy.agentAllowlist,receipt:receipt(s,'vault.agent.added',{vaultId:vault.vaultId,agentId},p.principalId)})});
 if(path==='/api/ledger/transfer'&&request.method==='POST')return withState(request,env,async(s,p)=>transfer(s,p,await readJson(request)));
 const vt=path.match(/^\/api\/vaults\/([^/]+)\/ledger\/transfer$/);if(vt&&request.method==='POST')return withState(request,env,async(s,p)=>{const body=await readJson(request);const vault=s.vaults.find(v=>v.vaultId===vt[1]);if(!vault)return json({error:'vault_not_found'},404);return transfer(s,p,{...body,fromWalletId:body.fromWalletId||vault.walletSystem.primaryWallet.walletId})});
 if(path==='/api/receipts'&&request.method==='GET')return withState(request,env,async(s)=>json({receipts:s.receipts,receiptHead:s.receiptHead}));
 if(path==='/api/samples'&&request.method==='GET')return json({auth:{header:'authorization: Bearer pk_demo_operator'},boundaries:'/api/boundaries',regulatedLive:'/api/regulated-live',secretReference:{provider:'cloudflare_secrets',secretRef:'BROKER_ALPACA_SANDBOX_KEY',scope:'broker'},brokerConnector:{broker:'alpaca_sandbox',secretHandles:['pxsh_example']},tokenRail:{asset:'PXCRED',mode:'internal_credit_or_testnet'},vaultCreate:{name:'Customer AI Ops Vault',agentId:'customer-agent-001',owner:'customer-operator',plan:'vault_api_subscription'},transfer:{asset:'PXUSD',amount:250}});
 return json({error:'not_found',path},404)}
function transfer(s,p,body){const from=s.wallets.find(w=>w.walletId===body.fromWalletId);const to=s.wallets.find(w=>w.walletId===body.toWalletId);const asset=body.asset||'PXUSD';const amount=Number(body.amount||0);if(body.mode==='live'||body.live===true)return json(denyLive('live_money_transfer'),403);if(!from||!to||amount<=0)return json({error:'invalid_transfer_request'},400);if(asset==='PXUSD'){const gate=canSpend(p,amount);if(!gate.ok)return json(gate,409)}if((from.balances[asset]||0)<amount)return json({error:'insufficient_paper_balance'},409);from.balances[asset]-=amount;to.balances[asset]=(to.balances[asset]||0)+amount;return json({transfer:{from:from.walletId,to:to.walletId,asset,amount,mode:'paper'},receipt:receipt(s,'ledger.transfer',body,p.principalId)})}
export{route,BOUNDARIES,DISABLED};export default{fetch:route};