import{auth,canSpend,hash,mkKvStore,mkMemoryStore,receipt,recover,snapshot}from'./vault-state.js';
import{BROKERS,GATES,denyLive,evaluateLiveGate,buildApprovalPacket,makeSecretHandle,makeBrokerConnector,makeInternalTokenRail,makePaperOrderProposal,makeTokenMovementProposal}from'./regulated-live.js';
const now=()=>new Date().toISOString(),memory=mkMemoryStore();
const BOUNDARIES=['no custody','no private keys','no live broker execution','no live money movement','no token sale','no public mainnet bridge','paper/testnet only'];
const DISABLED=['custody','private_key_import','seed_phrase_capture','live_broker_order','live_money_transfer','token_sale','yield_claim','redemption_claim','public_mainnet_bridge'];
const json=(body,status=200)=>new Response(JSON.stringify(body,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization,x-api-key'}});
const readJson=async(r)=>{try{return await r.json()}catch{return{}}};const blocked=c=>json({error:'boundary_blocked',capability:c,posture:'paper_testnet_only',boundaries:BOUNDARIES},403);
const storeFor=(env={})=>env.PARALLAX_VAULT_STATE?mkKvStore(env.PARALLAX_VAULT_STATE):memory;
const mkWallet=(b={})=>({walletId:`pxw_${hash(b).slice(3)}`,agentId:b.agentId||'external-agent',owner:b.owner||'external-owner',mode:'paper',balances:{PXUSD:Number(b.pxusd??10000),PXAI:Number(b.pxai??1000),PXCRED:0},connectors:b.connectors||[],limits:{dailyPXUSD:Number(b.dailyPXUSD??5000),requiresHumanAbove:Number(b.requiresHumanAbove??1000)},createdAt:now()});
const mkVault=(b={})=>{const vaultId=`pxv_${hash({b,at:now()}).slice(3)}`,wallet=mkWallet({agentId:b.agentId||'vault-agent',owner:b.owner||'vault-owner',pxusd:b.pxusd??50000,pxai:b.pxai??10000,connectors:['evm','solana','icp','bitcoin','cosmos']});return{vaultId,name:b.name||'Agent Swarm Vault',owner:b.owner||'vault-owner',mode:'paper',status:'active_sample',walletSystem:{primaryWallet:wallet,wallets:[wallet],outsideConnectors:[{id:'evm',status:'ready_to_connect',networks:['ethereum','base','polygon']},{id:'solana',status:'ready_to_connect',networks:['solana']},{id:'icp',status:'ready_to_connect',networks:['icp-local','icp-testnet']},{id:'bitcoin',status:'watch_only_ready',networks:['bitcoin']},{id:'cosmos',status:'ready_to_connect',networks:['cosmos','osmosis']}],policy:{agentAllowlist:[b.agentId||'vault-agent','agent-risk-gatekeeper','agent-receipt-writer'],humanThresholdPXUSD:1000,liveExecution:false,custody:false}},prebuilt:{tools:['policy-pack-alpha','receipt-room','ledger-reconciler','market-sentinel','billing-meter','connector-health'],ledgers:['parallax-paper-ledger','agent-credit-ledger','icp-local-ledger'],permissions:['read_balances','propose_transfer','request_receipt','tick_agent'],sampleApiKey:`pk_demo_${hash(vaultId).slice(3)}`},regulatedLive:{status:'disabled',secretHandles:[],brokerConnectors:[],internalTokenRails:[]},monetization:{plan:b.plan||'vault_api_subscription',metered:true,units:['vault/month','api_call','receipt','connector']},createdAt:now()}};
async function withState(request,env,fn){const store=storeFor(env),state=await store.load();state.secretHandles??=[];state.brokerConnectors??=[];state.internalTokenRails??=[];state.liveApprovalPackets??=[];if(!state.vaults.length){const vault=mkVault({name:'Demo Agent Swarm Vault',owner:'demo-operator',agentId:'external-demo-agent'});state.vaults.push(vault);state.wallets.push(vault.walletSystem.primaryWallet)}const a=auth(request,state);if(!a.ok)return json({error:a.error},401);const out=await fn(state,a.principal);await store.save(state);return out}
const boundaryResponse=()=>json({posture:'paper_testnet_only',readyForUse:true,boundaries:BOUNDARIES,disabledCapabilities:DISABLED,allowedCapabilities:['create_agent_vault','create_paper_wallet','register_secret_reference','register_broker_connector','register_internal_token_rail','simulate_paper_transfer','paper_broker_order_proposal','internal_token_movement_proposal','build_live_approval_packet','write_receipt','verify_recovery'],marketingSafeClaim:'PARALLAX provides paper/testnet agent vaults and receipt evidence for external AI agents without custody, private keys, live brokerage, live money movement, token sales, or public mainnet bridge execution.'});
function isForbiddenPath(path){return /custody|private[-_]?key|seed|token[-_]?sale|yield|redeem|mainnet[-_]?bridge/i.test(path)}
async function route(request,env={}){const url=new URL(request.url),path=url.pathname;if(request.method==='OPTIONS')return json({ok:true});
 if(path==='/api/regulated-live')return json({posture:'regulated_live_disabled_until_approved',brokers:BROKERS,requiredGates:GATES,capabilities:['secret_reference_registration','broker_connector_registration','internal_token_rail_registration','sandbox_order_proposal','approval_packet_build'],disabled:['raw_secret_storage','private_key_storage','live_order_submit','live_money_transfer','token_sale','public_mainnet_bridge']});
 if(path==='/api/live/gate')return json(evaluateLiveGate(Object.fromEntries([...url.searchParams].map(([k,v])=>[k,v==='true']))));
 if(path==='/api/live/approval-packet'&&request.method==='POST')return withState(request,env,async(s,p)=>{const packet=buildApprovalPacket(await readJson(request));s.liveApprovalPackets.push(packet);return json({packet,receipt:receipt(s,'regulated_live.approval_packet.created',packet,p.principalId)},201)});
 if(['/api/brokers/execute','/api/live/execute','/api/live-money/transfer','/api/token-sale'].includes(path))return json(denyLive(path),403);
 if(isForbiddenPath(path))return blocked(path);if(path==='/api/boundaries')return boundaryResponse();
 if(path==='/api/status')return withState(request,env,async(s)=>json({ok:true,platform:'PARALLAX Agent Vault API',posture:'paper_testnet_first',regulatedLive:'disabled_until_approved',stateStore:storeFor(env).kind,persistence:storeFor(env).kind==='cloudflare-kv'?'durable_kv':'memory_fallback',receiptHead:s.receiptHead,servers:['agent-control','vault-wallet-ledger','proof-room','billing-meter'],boundaries:BOUNDARIES,disabledCapabilities:DISABLED}));
 if(path==='/api/recovery')return withState(request,env,async(s)=>json(recover(s,url.searchParams.get('hash'))));if(path==='/api/snapshot')return withState(request,env,async(s)=>json(snapshot(s)));
 if(path==='/api/secrets'&&request.method==='GET')return withState(request,env,async(s)=>json({secretHandles:s.secretHandles,storesSecretValues:false}));
 if(path==='/api/secrets'&&request.method==='POST')return withState(request,env,async(s,p)=>{const h=makeSecretHandle(await readJson(request));s.secretHandles.push(h);return json({secretHandle:h,receipt:receipt(s,'secret.reference.registered',h,p.principalId)},201)});
 if(path==='/api/brokers/adapters')return json({brokers:BROKERS,adapterContract:{mode:'paper_or_sandbox',required:['secretHandles','riskLimits','receipt_write'],disabled:['live_order_submit','cash_withdrawal','margin_enable']}});
 if(path==='/api/brokers'&&request.method==='GET')return withState(request,env,async(s)=>json({brokerConnectors:s.brokerConnectors,supported:BROKERS,liveExecution:false}));
 if(path==='/api/brokers'&&request.method==='POST')return withState(request,env,async(s,p)=>{const c=makeBrokerConnector(await readJson(request));s.brokerConnectors.push(c);return json({brokerConnector:c,receipt:receipt(s,'broker.connector.registered',c,p.principalId)},201)});
 if(path==='/api/brokers/paper-order'&&request.method==='POST')return withState(request,env,async(s,p)=>{const po=makePaperOrderProposal(await readJson(request));return json({paperOrder:po,receipt:receipt(s,'broker.paper_order.proposed',po,p.principalId)},201)});
 if(path==='/api/token-rails'&&request.method==='GET')return withState(request,env,async(s)=>json({internalTokenRails:s.internalTokenRails,liveRedeemability:false}));
 if(path==='/api/token-rails'&&request.method==='POST')return withState(request,env,async(s,p)=>{const rail=makeInternalTokenRail(await readJson(request));s.internalTokenRails.push(rail);return json({internalTokenRail:rail,receipt:receipt(s,'internal_token_rail.registered',rail,p.principalId)},201)});
 if(path==='/api/token-rails/proposal'&&request.method==='POST')return withState(request,env,async(s,p)=>{const mv=makeTokenMovementProposal(await readJson(request));return json({movement:mv,receipt:receipt(s,'internal_token.movement.proposed',mv,p.principalId)},201)});
 if(path==='/api/token-rails/live-transfer'&&request.method==='POST')return json(denyLive('live_money_movement_through_internal_tokens',{safeRoute:'POST /api/token-rails/proposal'}),403);
 if(path==='/api/monetization')return json({paths:['vault_api_subscription','agent_wallet_metering','receipt_room_enterprise','connector_marketplace','managed_agent_ops','white_label_vaults','regulated_live_readiness_package'],boundary:'pricing_not_set_in_code',forbidden:['token_sale','yield_claim','redemption_claim']});
 if(path==='/api/agents'&&request.method==='GET')return withState(request,env,async(s)=>json({agents:s.agents}));if(path==='/api/agents/tick'&&request.method==='POST')return withState(request,env,async(s,p)=>{const b=await readJson(request),agent=s.agents.find(a=>a.id===b.agentId)||s.agents[0];agent.status='running';agent.lastTick=now();return json({agent,receipt:receipt(s,'agent.tick',agent,p.principalId)})});
 if(path==='/api/ledgers'&&request.method==='GET')return withState(request,env,async(s)=>json({ledgers:s.ledgers}));if(path==='/api/wallets'&&request.method==='GET')return withState(request,env,async(s)=>json({wallets:s.wallets}));
 if(path==='/api/wallets'&&request.method==='POST')return withState(request,env,async(s,p)=>{const w=mkWallet(await readJson(request));s.wallets.push(w);return json({wallet:w,receipt:receipt(s,'wallet.created',w,p.principalId),upgradePath:'POST /api/vaults creates a full vault around the wallet system'},201)});
 if(path==='/api/vaults'&&request.method==='GET')return withState(request,env,async(s)=>json({vaults:s.vaults}));if(path==='/api/vaults'&&request.method==='POST')return withState(request,env,async(s,p)=>{const v=mkVault(await readJson(request));s.vaults.push(v);s.wallets.push(v.walletSystem.primaryWallet);return json({vault:v,apiKey:v.prebuilt.sampleApiKey,receipt:receipt(s,'vault.created',v,p.principalId)},201)});
 const vm=path.match(/^\/api\/vaults\/([^/]+)$/);if(vm&&request.method==='GET')return withState(request,env,async(s)=>{const v=s.vaults.find(x=>x.vaultId===vm[1]);return v?json({vault:v}):json({error:'vault_not_found'},404)});
 const cm=path.match(/^\/api\/vaults\/([^/]+)\/connectors$/);if(cm&&request.method==='POST')return withState(request,env,async(s,p)=>{const b=await readJson(request),v=s.vaults.find(x=>x.vaultId===cm[1]);if(!v)return json({error:'vault_not_found'},404);const c={id:b.id||'custom_connector',status:'linked_sample',networks:b.networks||['paper']};v.walletSystem.outsideConnectors.push(c);return json({connector:c,receipt:receipt(s,'vault.connector.linked',{vaultId:v.vaultId,connector:c},p.principalId)})});
 const am=path.match(/^\/api\/vaults\/([^/]+)\/agents$/);if(am&&request.method==='POST')return withState(request,env,async(s,p)=>{const b=await readJson(request),v=s.vaults.find(x=>x.vaultId===am[1]);if(!v)return json({error:'vault_not_found'},404);const agentId=b.agentId||`agent-${hash(b).slice(3)}`;v.walletSystem.policy.agentAllowlist.push(agentId);return json({agentId,allowlist:v.walletSystem.policy.agentAllowlist,receipt:receipt(s,'vault.agent.added',{vaultId:v.vaultId,agentId},p.principalId)})});
 if(path==='/api/ledger/transfer'&&request.method==='POST')return withState(request,env,async(s,p)=>transfer(s,p,await readJson(request)));const vt=path.match(/^\/api\/vaults\/([^/]+)\/ledger\/transfer$/);if(vt&&request.method==='POST')return withState(request,env,async(s,p)=>{const b=await readJson(request),v=s.vaults.find(x=>x.vaultId===vt[1]);if(!v)return json({error:'vault_not_found'},404);return transfer(s,p,{...b,fromWalletId:b.fromWalletId||v.walletSystem.primaryWallet.walletId})});
 if(path==='/api/receipts'&&request.method==='GET')return withState(request,env,async(s)=>json({receipts:s.receipts,receiptHead:s.receiptHead}));
 if(path==='/api/samples'&&request.method==='GET')return json({auth:{header:'authorization: Bearer pk_demo_operator'},regulatedLive:'/api/regulated-live',liveGate:'/api/live/gate',approvalPacket:'POST /api/live/approval-packet',brokerAdapters:'/api/brokers/adapters',paperOrder:'POST /api/brokers/paper-order',tokenMovement:'POST /api/token-rails/proposal'});
 return json({error:'not_found',path},404)}
function transfer(s,p,b){const from=s.wallets.find(w=>w.walletId===b.fromWalletId),to=s.wallets.find(w=>w.walletId===b.toWalletId),asset=b.asset||'PXUSD',amount=Number(b.amount||0);if(b.mode==='live'||b.live===true)return json(denyLive('live_money_transfer'),403);if(!from||!to||amount<=0)return json({error:'invalid_transfer_request'},400);if(asset==='PXUSD'){const gate=canSpend(p,amount);if(!gate.ok)return json(gate,409)}if((from.balances[asset]||0)<amount)return json({error:'insufficient_paper_balance'},409);from.balances[asset]-=amount;to.balances[asset]=(to.balances[asset]||0)+amount;return json({transfer:{from:from.walletId,to:to.walletId,asset,amount,mode:'paper'},receipt:receipt(s,'ledger.transfer',b,p.principalId)})}
export{route,BOUNDARIES,DISABLED};export default{fetch:route};