/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EdgeInput = IDL.Record({
  'relation' : IDL.Text,
  'toId' : IDL.Text,
  'fromId' : IDL.Text,
});
export const Edge = IDL.Record({
  'id' : IDL.Text,
  'relation' : IDL.Text,
  'beat' : IDL.Nat,
  'toId' : IDL.Text,
  'fromId' : IDL.Text,
});
export const GrantRecord = IDL.Record({
  'status' : IDL.Text,
  'grantType' : IDL.Text,
  'deadlineMs' : IDL.Int,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'amountUsd' : IDL.Nat,
});
export const LessonTool = IDL.Record({
  'id' : IDL.Text,
  'publicAccess' : IDL.Bool,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'description' : IDL.Text,
  'teksCodes' : IDL.Vec(IDL.Text),
  'toolType' : IDL.Text,
});
export const LedgerEntry = IDL.Record({
  'proofHash' : IDL.Text,
  'beat' : IDL.Nat,
  'phiDepth' : IDL.Nat,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'payload' : IDL.Text,
});
export const NodeInput = IDL.Record({
  'labelText' : IDL.Text,
  'nodeType' : IDL.Text,
});
export const Node = IDL.Record({
  'id' : IDL.Text,
  'beat' : IDL.Nat,
  'labelText' : IDL.Text,
  'nodeType' : IDL.Text,
});
export const SchoolTier = IDL.Variant({
  'Gold' : IDL.Null,
  'Bronze' : IDL.Null,
  'Silver' : IDL.Null,
});
export const SchoolRecord = IDL.Record({
  'id' : IDL.Text,
  'deployed' : IDL.Bool,
  'grantStatus' : IDL.Text,
  'name' : IDL.Text,
  'tier' : SchoolTier,
  'district' : IDL.Text,
  'contactEmail' : IDL.Text,
  'teksStandardsCodes' : IDL.Vec(IDL.Text),
  'canisterId' : IDL.Opt(IDL.Text),
});
export const TeksStandard = IDL.Record({
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'code' : IDL.Text,
  'lessonTools' : IDL.Vec(LessonTool),
  'description' : IDL.Text,
  'grade' : IDL.Text,
});
export const SovereignModel = IDL.Record({
  'id' : IDL.Text,
  'latinName' : IDL.Text,
  'meaning' : IDL.Text,
  'subIntelligence' : IDL.Text,
  'layer' : IDL.Text,
  'lastBeatActivated' : IDL.Int,
  'computation' : IDL.Text,
  'inputTypes' : IDL.Vec(IDL.Text),
  'microTokenId' : IDL.Nat32,
  'executionBinding' : IDL.Text,
  'maxMicroTokenOutput' : IDL.Nat,
  'beatActivationCount' : IDL.Nat,
});
export const ProtocolRecordPublic = IDL.Record({
  'id' : IDL.Text,
  'principle' : IDL.Text,
  'executionCount' : IDL.Nat,
  'lastFiredBeat' : IDL.Int,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'lastResult' : IDL.Text,
  'equation' : IDL.Text,
  'precedence' : IDL.Nat,
});
export const BankTxEntry = IDL.Record({
  'direction' : IDL.Variant({ 'in' : IDL.Null, 'out' : IDL.Null }),
  'asset' : IDL.Text,
  'note' : IDL.Text,
  'txId' : IDL.Text,
  'timestamp' : IDL.Nat,
  'amount' : IDL.Float64,
  'flagged' : IDL.Bool,
});
export const BankAccountEntry = IDL.Record({
  'kycTimestamp' : IDL.Nat,
  'thresholdLimit' : IDL.Float64,
  'ownerName' : IDL.Text,
  'accountId' : IDL.Text,
  'delegatedSigning' : IDL.Bool,
  'createdAt' : IDL.Nat,
  'role' : IDL.Variant({
    'institutional' : IDL.Null,
    'personal' : IDL.Null,
    'business' : IDL.Null,
  }),
  'icpBalance' : IDL.Float64,
  'ckBtcBalance' : IDL.Float64,
  'kycStatus' : IDL.Variant({
    'notStarted' : IDL.Null,
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'txHistory' : IDL.Vec(BankTxEntry),
  'ckEthBalance' : IDL.Float64,
});
export const EntityType = IDL.Variant({
  'internal' : IDL.Null,
  'external' : IDL.Null,
});
export const EntityState = IDL.Variant({
  'active' : IDL.Null,
  'transcended' : IDL.Null,
  'awakening' : IDL.Null,
  'dormant' : IDL.Null,
});
export const BirthEntity = IDL.Record({
  'id' : IDL.Text,
  'organType' : IDL.Text,
  'directive' : IDL.Text,
  'birthBeat' : IDL.Int,
  'birthTimestamp' : IDL.Int,
  'name' : IDL.Text,
  'goalStack' : IDL.Vec(IDL.Text),
  'activation' : IDL.Float64,
  'entityType' : EntityType,
  'messageLog' : IDL.Vec(IDL.Text),
  'entityState' : EntityState,
});
export const BirthAiState = IDL.Record({
  'lastBirthBeat' : IDL.Int,
  'totalTranscended' : IDL.Nat,
  'totalBorn' : IDL.Nat,
  'entities' : IDL.Vec(IDL.Tuple(IDL.Text, BirthEntity)),
});
export const DirectiveStatus = IDL.Variant({
  'building' : IDL.Null,
  'complete' : IDL.Null,
  'failed' : IDL.Null,
  'parsed' : IDL.Null,
});
export const TargetType = IDL.Variant({
  'protocol' : IDL.Null,
  'entity' : IDL.Null,
  'agent' : IDL.Null,
  'canister' : IDL.Null,
  'queryTarget' : IDL.Null,
});
export const BuilderDirective = IDL.Record({
  'id' : IDL.Text,
  'status' : DirectiveStatus,
  'rawText' : IDL.Text,
  'parameters' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'parsedIntent' : IDL.Text,
  'timestamp' : IDL.Int,
  'targetType' : TargetType,
  'outputId' : IDL.Opt(IDL.Text),
});
export const BuilderState = IDL.Record({
  'directives' : IDL.Vec(IDL.Tuple(IDL.Text, BuilderDirective)),
  'totalFailed' : IDL.Nat,
  'totalBuilt' : IDL.Nat,
});
export const CardiacState = IDL.Record({
  'heartbeatActive' : IDL.Bool,
  'omnisFiredCount' : IDL.Nat,
  'hrvBound' : IDL.Float64,
  'coherenceDirection' : IDL.Int,
  'coherenceTarget' : IDL.Float64,
  'deoxygenationAlarms' : IDL.Nat,
  'lastBeatTime' : IDL.Int,
  'neurochemicalLevels' : IDL.Vec(IDL.Float64),
  'oxygenationScore' : IDL.Float64,
  'heartRate' : IDL.Float64,
  'globalCoherence' : IDL.Float64,
  'kuramotoR' : IDL.Float64,
  'strokeVolume' : IDL.Float64,
  'entanglaCarrier' : IDL.Float64,
  'lastOmnisFireBeat' : IDL.Nat,
});
export const CodexEntry = IDL.Record({
  'id' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'numericalValue' : IDL.Float64,
  'enforcementAgi' : IDL.Text,
  'ancientSource' : IDL.Text,
  'principleOneLine' : IDL.Text,
  'computation' : IDL.Text,
  'category' : IDL.Text,
  'formula' : IDL.Text,
});
export const ContextRouterState = IDL.Record({
  'totalBeatRoutes' : IDL.Nat,
  'microTokenBudgetPerBeat' : IDL.Nat,
  'avgResonanceScore' : IDL.Float64,
});
export const CreatorReserveState = IDL.Record({
  'totalUsdEquiv' : IDL.Float64,
  'founderName' : IDL.Text,
  'withdrawableIcp' : IDL.Float64,
  'btcReserve' : IDL.Float64,
  'totalWithdrawn' : IDL.Float64,
  'icpReserve' : IDL.Float64,
  'mtcReserve' : IDL.Float64,
  'founderAccountId' : IDL.Text,
  'ethReserve' : IDL.Float64,
});
export const DriveState = IDL.Record({
  'consecutiveDriveBeats' : IDL.Nat,
  'px_driveStrengths' : IDL.Vec(IDL.Float64),
  'dominantDriveId' : IDL.Nat,
});
export const EngineState = IDL.Record({
  'jubileeCount' : IDL.Nat,
  'qbSuperradiance' : IDL.Float64,
  'shemaLastCheckBeat' : IDL.Nat,
  'anointedStateActive' : IDL.Bool,
  'axisCanisterId' : IDL.Text,
  'qbShell3Discharge' : IDL.Float64,
  'axisEagleElevation' : IDL.Float64,
  'qmemCanisterId' : IDL.Text,
  'fluxCanisterId' : IDL.Text,
  'jubileeLastBeat' : IDL.Nat,
  'resonexCanisterId' : IDL.Text,
  'kalmanConfidence' : IDL.Float64,
  'axisElephantDist' : IDL.Float64,
  'firePillarCount' : IDL.Nat,
  'firePillarActive' : IDL.Bool,
  'sevenSpiritsScore' : IDL.Float64,
  'axisEagleAccel' : IDL.Float64,
  'axisEagleCurvature' : IDL.Float64,
  'shemaIntegrityScore' : IDL.Float64,
  'prophetConvergenceCount' : IDL.Nat,
  'axisElephantRecall' : IDL.Float64,
  'prophetFunctionArmed' : IDL.Bool,
  'qbSuperchargeRate' : IDL.Float64,
});
export const FormaState = IDL.Record({
  'spectralCoherence' : IDL.Float64,
  'projectionPlus10000' : IDL.Text,
  'beatCount' : IDL.Nat,
  'projectionPlus1000' : IDL.Text,
  'compoundRatePerBeat' : IDL.Float64,
  'capital' : IDL.Float64,
  'vonNeumannEntropy' : IDL.Float64,
});
export const FullWalletSnapshot = IDL.Record({
  'totalUsdEquiv' : IDL.Float64,
  'creatorBtc' : IDL.Float64,
  'creatorEth' : IDL.Float64,
  'creatorIcp' : IDL.Float64,
  'creatorMtc' : IDL.Float64,
  'btcBalance' : IDL.Float64,
  'withdrawableIcp' : IDL.Float64,
  'beatCount' : IDL.Nat,
  'icpBalance' : IDL.Float64,
  'ethBalance' : IDL.Float64,
  'totalWithdrawn' : IDL.Float64,
  'tokenCount' : IDL.Nat,
  'mtcCirculating' : IDL.Float64,
  'neuronCount' : IDL.Nat,
});
export const GenesisState = IDL.Record({
  'sl6Emission' : IDL.Float64,
  'genesisTimestamp' : IDL.Int,
  'sl2Resonance' : IDL.Float64,
  'beatCount' : IDL.Nat,
  'doctrineHash' : IDL.Text,
  'sl3Coherence' : IDL.Float64,
  'creatorName' : IDL.Text,
  'sl4Depth' : IDL.Float64,
  'creatorYear' : IDL.Nat,
  'alfredoLawActive' : IDL.Bool,
  'creatorJurisdiction' : IDL.Text,
  'sl7Depth' : IDL.Float64,
  'alfredoLawHash' : IDL.Text,
  'genesisLocked' : IDL.Bool,
  'sl5Amplitude' : IDL.Float64,
  'creatorTitle' : IDL.Text,
  'sl1Score' : IDL.Float64,
});
export const GrantRecord_School = IDL.Record({
  'status' : IDL.Text,
  'deadlineMs' : IDL.Int,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'amountUsd' : IDL.Nat,
  'program' : IDL.Text,
});
export const JacobRung = IDL.Record({
  'multiplier' : IDL.Float64,
  'rungNumber' : IDL.Nat,
  'labelText' : IDL.Text,
  'isCurrent' : IDL.Bool,
});
export const JacobsLadderState = IDL.Record({
  'velocity' : IDL.Float64,
  'currentRung' : IDL.Nat,
  'saceciTarget' : IDL.Float64,
  'rungs' : IDL.Vec(JacobRung),
});
export const KycRecord = IDL.Record({
  'status' : IDL.Variant({
    'notStarted' : IDL.Null,
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'accountId' : IDL.Text,
  'retryCount' : IDL.Nat,
  'lastChecked' : IDL.Nat,
  'apiResponse' : IDL.Text,
});
export const ModelRegistryState = IDL.Record({
  'lastActivated' : IDL.Text,
  'totalActivations' : IDL.Nat,
  'totalModels' : IDL.Nat,
  'microTokensConsumedTotal' : IDL.Nat,
});
export const NeuronGroup = IDL.Record({
  'dissolveYears' : IDL.Float64,
  'count' : IDL.Nat,
  'fibIndex' : IDL.Nat,
  'groupId' : IDL.Text,
  'substrate' : IDL.Text,
  'purpose' : IDL.Text,
  'policy' : IDL.Text,
});
export const NeuronFleetState = IDL.Record({
  'groups' : IDL.Vec(NeuronGroup),
  'fieldNodes' : IDL.Nat,
  'neuronsPerNode' : IDL.Nat,
  'totalNeurons' : IDL.Nat,
});
export const NovaCognitiveLanguage = IDL.Record({
  'id' : IDL.Text,
  'latinName' : IDL.Text,
  'executionCount' : IDL.Nat,
  'coherenceGateScore' : IDL.Float64,
  'primaryObjects' : IDL.Vec(IDL.Text),
  'englishDomain' : IDL.Text,
  'runtimePhase' : IDL.Text,
  'lastBeatExecuted' : IDL.Int,
  'stack' : IDL.Text,
  'executionBinding' : IDL.Text,
});
export const NovaRuntimeState = IDL.Record({
  'runtimePhase' : IDL.Text,
  'languages' : IDL.Vec(NovaCognitiveLanguage),
  'lastBeatExecuted' : IDL.Int,
  'totalExecutionCount' : IDL.Nat,
  'novaVersion' : IDL.Text,
});
export const RegistryEntry = IDL.Record({
  'deployed' : IDL.Int,
  'organType' : IDL.Text,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'unreachable' : IDL.Null,
    'degraded' : IDL.Null,
  }),
  'messages' : IDL.Nat,
  'errors' : IDL.Nat,
  'latencyMs' : IDL.Int,
  'cycles' : IDL.Nat,
  'lastHeartbeat' : IDL.Int,
  'healthScore' : IDL.Float64,
  'principalId' : IDL.Opt(IDL.Principal),
  'canisterId' : IDL.Text,
});
export const OrganismRecord = IDL.Record({
  'active' : IDL.Bool,
  'proofDepth' : IDL.Nat,
  'beat' : IDL.Nat,
  'name' : IDL.Text,
  'earnings' : IDL.Float64,
  'coherence' : IDL.Float64,
  'fieldType' : IDL.Nat,
  'canisterId' : IDL.Text,
});
export const SubOrganismRecord = IDL.Record({
  'active' : IDL.Bool,
  'tier' : IDL.Nat,
  'parentId' : IDL.Text,
  'royaltyRate' : IDL.Float64,
  'canisterId' : IDL.Text,
});
export const OrganismState = IDL.Record({
  'organisms' : IDL.Vec(OrganismRecord),
  'franchiseCutRate' : IDL.Float64,
  'franchiseCount' : IDL.Nat,
  'championPool' : IDL.Float64,
  'totalOrganismEarnings' : IDL.Float64,
  'activeCount' : IDL.Nat,
  'subOrganisms' : IDL.Vec(SubOrganismRecord),
});
export const ProfitState = IDL.Record({
  'totalAllStreams' : IDL.Float64,
  'streams' : IDL.Vec(IDL.Float64),
});
export const ProtocolCategory = IDL.Variant({
  'Law' : IDL.Null,
  'Reasoning' : IDL.Null,
  'Model' : IDL.Null,
  'Organ' : IDL.Null,
  'Behavior' : IDL.Null,
});
export const ProtocolResult = IDL.Variant({
  'skipped' : IDL.Null,
  'failed' : IDL.Null,
  'passed' : IDL.Null,
});
export const ProtocolRecord = IDL.Record({
  'id' : IDL.Text,
  'principle' : IDL.Text,
  'executionCount' : IDL.Nat,
  'lastFiredBeat' : IDL.Int,
  'name' : IDL.Text,
  'category' : ProtocolCategory,
  'lastResult' : ProtocolResult,
  'equation' : IDL.Text,
  'precedence' : IDL.Nat,
});
export const ProtocolRegistry = IDL.Record({
  'totalExecutions' : IDL.Nat,
  'protocols' : IDL.Vec(IDL.Tuple(IDL.Text, ProtocolRecord)),
  'lastScanBeat' : IDL.Int,
});
export const RegistryState = IDL.Record({
  'lastUpdated' : IDL.Int,
  'entries' : IDL.Vec(IDL.Tuple(IDL.Text, RegistryEntry)),
});
export const SchoolRegistry = IDL.Record({
  'grants' : IDL.Vec(GrantRecord_School),
  'totalDeployed' : IDL.Nat,
  'schools' : IDL.Vec(SchoolRecord),
  'lastUpdatedMs' : IDL.Int,
  'teksStandards' : IDL.Vec(TeksStandard),
});
export const ShellState = IDL.Record({
  'rValues' : IDL.Vec(IDL.Float64),
  'shell3Coherence' : IDL.Float64,
  'activations' : IDL.Vec(IDL.Float64),
  'shell3BeeGate' : IDL.Vec(IDL.Float64),
});
export const SignalState = IDL.Record({
  'eagleSignal' : IDL.Float64,
  'orcaSignal' : IDL.Float64,
  'dolphinSignal' : IDL.Float64,
  'thyroidT3' : IDL.Float64,
  'thyroidT4' : IDL.Float64,
  'hiveSignal' : IDL.Float64,
  'crowSignal' : IDL.Float64,
  'wolfSignal' : IDL.Float64,
  'octopusSignal' : IDL.Float64,
  'respirationRate' : IDL.Float64,
  'heartRate' : IDL.Float64,
  'sharkSignal' : IDL.Float64,
  'cortisol' : IDL.Float64,
  'elephantSignal' : IDL.Float64,
});
export const TokenEntry = IDL.Record({
  'homeCanister' : IDL.Text,
  'circulatingSupply' : IDL.Float64,
  'mintTrigger' : IDL.Text,
  'name' : IDL.Text,
  'managingAgi' : IDL.Text,
  'totalSupply' : IDL.Float64,
  'creatorReserveBalance' : IDL.Float64,
  'burnTrigger' : IDL.Text,
  'priceIcp' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TreasuryState = IDL.Record({
  'btcHardFloor' : IDL.Float64,
  'icpStaked' : IDL.Float64,
  'icpYieldRate' : IDL.Float64,
  'creatorMtcReserve' : IDL.Float64,
  'mtcPrice' : IDL.Float64,
  'creatorEthReserve' : IDL.Float64,
  'btcBalance' : IDL.Float64,
  'tokenBalances' : IDL.Vec(IDL.Float64),
  'clearanceReserves' : IDL.Vec(IDL.Float64),
  'creatorWithdrawableIcp' : IDL.Float64,
  'ethPrice' : IDL.Float64,
  'icpBalance' : IDL.Float64,
  'btcNetworkCongestion' : IDL.Float64,
  'ethRocketPoolRate' : IDL.Float64,
  'btcMempoolFeeRate' : IDL.Float64,
  'creatorTotalUsdEquiv' : IDL.Float64,
  'ethBalance' : IDL.Float64,
  'ethYieldRate' : IDL.Float64,
  'totalWithdrawn' : IDL.Float64,
  'btcPrice' : IDL.Float64,
  'icpPrice' : IDL.Float64,
  'icpAccruedYield' : IDL.Float64,
  'ethLidoRate' : IDL.Float64,
  'creatorBtcReserve' : IDL.Float64,
  'mtcBurned' : IDL.Float64,
  'mtcGenesisSupply' : IDL.Float64,
  'mtcCirculating' : IDL.Float64,
  'creatorIcpReserve' : IDL.Float64,
});
export const TxMonitoringState = IDL.Record({
  'institutionalThreshold' : IDL.Float64,
  'totalMonitored' : IDL.Nat,
  'flaggedCount' : IDL.Nat,
  'lastFlaggedAt' : IDL.Nat,
  'personalThreshold' : IDL.Float64,
  'businessThreshold' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Text,
  'name' : IDL.Text,
});
export const WithdrawalLogEntry = IDL.Record({
  'error' : IDL.Opt(IDL.Text),
  'toPrincipal' : IDL.Text,
  'blockIndex' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
  'amount' : IDL.Float64,
});
export const FrntDemo = IDL.Record({
  'visaFeeBps' : IDL.Nat,
  'demoActive' : IDL.Bool,
  'phantomFeeBps' : IDL.Nat,
  'visaBottleneckSolved' : IDL.Bool,
  'visaSettlementMs' : IDL.Nat,
  'lastRunMs' : IDL.Int,
  'phantomSettlementMs' : IDL.Nat,
});
export const NodeProvider = IDL.Record({
  'entity' : IDL.Text,
  'status' : IDL.Text,
  'gen3Ready' : IDL.Bool,
  'bslWhitelisted' : IDL.Bool,
  'lincolnNodes' : IDL.Nat,
  'cheyenneNodes' : IDL.Nat,
  'targetRegion' : IDL.Text,
});
export const MilestoneStatus = IDL.Variant({
  'Complete' : IDL.Null,
  'Critical' : IDL.Null,
  'InProgress' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Milestone = IDL.Record({
  'id' : IDL.Text,
  'status' : MilestoneStatus,
  'title' : IDL.Text,
  'deadlineMs' : IDL.Int,
  'notes' : IDL.Text,
});
export const LegislativeTimeline = IDL.Record({
  'billReadyMs' : IDL.Int,
  'unicameralSession' : IDL.Text,
  'hardwareDeadlineMs' : IDL.Int,
  'milestones' : IDL.Vec(Milestone),
});
export const Partnership = IDL.Record({
  'status' : IDL.Text,
  'contact' : IDL.Text,
  'partnerType' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
});
export const Facility = IDL.Record({
  'publicPower' : IDL.Bool,
  'stateCode' : IDL.Text,
  'city' : IDL.Text,
  'internetBackbone' : IDL.Bool,
  'address' : IDL.Text,
  'powerCostRank' : IDL.Text,
  'vaultGrade' : IDL.Bool,
});
export const WyomingState = IDL.Record({
  'charterGenesisHash' : IDL.Text,
  'grants' : IDL.Vec(GrantRecord),
  'frntDemo' : FrntDemo,
  'nodeProvider' : NodeProvider,
  'lastUpdatedMs' : IDL.Int,
  'legislative' : LegislativeTimeline,
  'partnerships' : IDL.Vec(Partnership),
  'facility' : Facility,
});
export const FullPxState = IDL.Record({
  'regime' : IDL.Text,
  'jacobRung' : IDL.Nat,
  'beat' : IDL.Nat,
  'novaHealth' : IDL.Float64,
  'sacesiTarget' : IDL.Float64,
  'novelty' : IDL.Float64,
  'dominantDrive' : IDL.Text,
  'patentCount' : IDL.Nat,
  'aresArmed' : IDL.Bool,
  'lawScore' : IDL.Float64,
  'coherence' : IDL.Float64,
  'miningOutput' : IDL.Float64,
  'genesisActivated' : IDL.Bool,
  'formaCapital' : IDL.Float64,
  'mthBalance' : IDL.Float64,
  'gtkBalance' : IDL.Float64,
  'mrcBalance' : IDL.Float64,
});
export const ContextSlice = IDL.Record({
  'microTokenBudget' : IDL.Nat,
  'resonanceScore' : IDL.Float64,
  'selectedModelIds' : IDL.Vec(IDL.Text),
  'microTokensUsed' : IDL.Nat,
  'beatTimestamp' : IDL.Int,
});
export const HealthReport = IDL.Record({
  'organType' : IDL.Text,
  'messages' : IDL.Nat,
  'errors' : IDL.Nat,
  'latencyMs' : IDL.Int,
  'cycles' : IDL.Nat,
  'timestamp' : IDL.Int,
  'healthScore' : IDL.Float64,
});

export const idlService = IDL.Service({
  'activateGenesis' : IDL.Func([IDL.Text], [IDL.Text], []),
  'addEdge' : IDL.Func([EdgeInput], [Edge], []),
  'addGrant' : IDL.Func([GrantRecord], [], []),
  'addLessonTool' : IDL.Func([IDL.Text, LessonTool], [], []),
  'addMessage' : IDL.Func([IDL.Text], [LedgerEntry], []),
  'addNode' : IDL.Func([NodeInput], [Node], []),
  'addSchool' : IDL.Func([SchoolRecord], [], []),
  'addTeksStandard' : IDL.Func([TeksStandard], [], []),
  'birthAI' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createBankAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deploySchoolCanister' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'entityLearn' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'entityRecall' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'entitySetGoal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'entitySpeak' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'executeBuilderDirective' : IDL.Func([IDL.Text], [IDL.Text], []),
  'executeNovaEngine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'exportFinCEN' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getAgiStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'memoria' : IDL.Record({
            'lex' : IDL.Text,
            'doctrineVerified' : IDL.Bool,
          }),
          'computator' : IDL.Record({
            'phi' : IDL.Float64,
            'fibonacciSeries' : IDL.Vec(IDL.Nat),
            'goldenAngle' : IDL.Float64,
            'schumannHz' : IDL.Float64,
          }),
          'gubernator' : IDL.Record({
            'voteCount' : IDL.Nat,
            'neuronGroups' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
          'custoditor' : IDL.Record({ 'reroutedNodes' : IDL.Vec(IDL.Text) }),
          'explorator' : IDL.Record({ 'topNodes' : IDL.Vec(IDL.Text) }),
          'liberator' : IDL.Record({
            'lastBlockIndex' : IDL.Opt(IDL.Nat),
            'totalWithdrawals' : IDL.Nat,
            'ready' : IDL.Bool,
          }),
          'dispensator' : IDL.Record({ 'totalDisbursed' : IDL.Float64 }),
        }),
      ],
      ['query'],
    ),
  'getAllModels' : IDL.Func([], [IDL.Vec(SovereignModel)], ['query']),
  'getAllProtocols' : IDL.Func([], [IDL.Vec(ProtocolRecordPublic)], ['query']),
  'getAuditCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBankAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(BankAccountEntry)],
      ['query'],
    ),
  'getBankingSsuState' : IDL.Func(
      [],
      [
        IDL.Record({
          'beatCount' : IDL.Nat,
          'kuramotoR' : IDL.Float64,
          'aegisStatus' : IDL.Text,
          'genesisHash' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getBankingYield' : IDL.Func(
      [],
      [
        IDL.Record({
          'weeklyEst' : IDL.Float64,
          'neuronGroupStatus' : IDL.Text,
          'dailyMaturityEst' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getBeatCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBirthAiState' : IDL.Func([], [BirthAiState], ['query']),
  'getBtcBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getBuilderState' : IDL.Func([], [BuilderState], ['query']),
  'getCardiacState' : IDL.Func([], [CardiacState], ['query']),
  'getCodexById' : IDL.Func([IDL.Text], [IDL.Opt(CodexEntry)], ['query']),
  'getCodexMathematicus' : IDL.Func([], [IDL.Vec(CodexEntry)], ['query']),
  'getContextRouterState' : IDL.Func([], [ContextRouterState], ['query']),
  'getCreatorPrincipalLocked' : IDL.Func([], [IDL.Bool], ['query']),
  'getCreatorReserve' : IDL.Func([], [CreatorReserveState], ['query']),
  'getCreatorWithdrawableIcp' : IDL.Func([], [IDL.Float64], ['query']),
  'getDomLibStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'verificatorChecks' : IDL.Nat,
          'confirmatorCount' : IDL.Nat,
          'auditorCount' : IDL.Nat,
          'protectorBlocks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDriveState' : IDL.Func([], [DriveState], ['query']),
  'getEdges' : IDL.Func([], [IDL.Vec(Edge)], ['query']),
  'getEngineState' : IDL.Func([], [EngineState], ['query']),
  'getEthBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getFlaggedTransactions' : IDL.Func([], [IDL.Vec(BankTxEntry)], ['query']),
  'getFormaState' : IDL.Func([], [FormaState], ['query']),
  'getFounderAccountId' : IDL.Func([], [IDL.Text], ['query']),
  'getFullWalletSnapshot' : IDL.Func([], [FullWalletSnapshot], ['query']),
  'getGenesisState' : IDL.Func([], [GenesisState], ['query']),
  'getGrantsByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GrantRecord_School)],
      ['query'],
    ),
  'getIcpBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getJacobsLadder' : IDL.Func([], [JacobsLadderState], ['query']),
  'getKuramotoR' : IDL.Func([], [IDL.Float64], ['query']),
  'getKycEndpoint' : IDL.Func([], [IDL.Text], ['query']),
  'getKycStatus' : IDL.Func([IDL.Text], [IDL.Opt(KycRecord)], ['query']),
  'getLessonToolsByGrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LessonTool)],
      ['query'],
    ),
  'getLessonToolsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LessonTool)],
      ['query'],
    ),
  'getMemoriaNns' : IDL.Func(
      [],
      [IDL.Record({ 'lex' : IDL.Text, 'verified' : IDL.Bool })],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
  'getMicroTokenBudget' : IDL.Func([], [IDL.Nat], ['query']),
  'getModel' : IDL.Func([IDL.Text], [IDL.Opt(SovereignModel)], ['query']),
  'getModelCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getModelRegistryState' : IDL.Func([], [ModelRegistryState], ['query']),
  'getMtcCirculating' : IDL.Func([], [IDL.Float64], ['query']),
  'getNeuronFleet' : IDL.Func([], [NeuronFleetState], ['query']),
  'getNodes' : IDL.Func([], [IDL.Vec(Node)], ['query']),
  'getNovaActiveLanguages' : IDL.Func(
      [],
      [IDL.Vec(NovaCognitiveLanguage)],
      ['query'],
    ),
  'getNovaLanguageById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(NovaCognitiveLanguage)],
      ['query'],
    ),
  'getNovaLanguageRegistry' : IDL.Func(
      [],
      [IDL.Vec(NovaCognitiveLanguage)],
      ['query'],
    ),
  'getNovaLanguagesByStack' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NovaCognitiveLanguage)],
      ['query'],
    ),
  'getNovaRuntimeState' : IDL.Func([], [NovaRuntimeState], ['query']),
  'getOrganHealth' : IDL.Func([IDL.Text], [IDL.Opt(RegistryEntry)], ['query']),
  'getOrganismState' : IDL.Func([], [OrganismState], ['query']),
  'getProfitState' : IDL.Func([], [ProfitState], ['query']),
  'getProtocolById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProtocolRecordPublic)],
      ['query'],
    ),
  'getProtocolLog' : IDL.Func([], [IDL.Vec(ProtocolRecordPublic)], ['query']),
  'getProtocolRegistry' : IDL.Func([], [ProtocolRegistry], ['query']),
  'getProtocolsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProtocolRecordPublic)],
      ['query'],
    ),
  'getPublicCurriculum' : IDL.Func([], [IDL.Vec(TeksStandard)], ['query']),
  'getRecentAudit' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
  'getRecentSettle' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
  'getRegistryCoherence' : IDL.Func([], [IDL.Float64], ['query']),
  'getRegistryEntries' : IDL.Func([], [IDL.Vec(RegistryEntry)], ['query']),
  'getRegistryState' : IDL.Func([], [RegistryState], ['query']),
  'getSchoolByDistrict' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SchoolRecord)],
      ['query'],
    ),
  'getSchoolRegistry' : IDL.Func([], [SchoolRegistry], ['query']),
  'getShellState' : IDL.Func([], [ShellState], ['query']),
  'getSignalState' : IDL.Func([], [SignalState], ['query']),
  'getTeksStandard' : IDL.Func([IDL.Text], [IDL.Opt(TeksStandard)], ['query']),
  'getTokenBySymbol' : IDL.Func([IDL.Text], [IDL.Opt(TokenEntry)], ['query']),
  'getTokenRegistry' : IDL.Func([], [IDL.Vec(TokenEntry)], ['query']),
  'getTotalProfit' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalWithdrawn' : IDL.Func([], [IDL.Float64], ['query']),
  'getTreasuryState' : IDL.Func([], [TreasuryState], ['query']),
  'getTxMonitoringState' : IDL.Func([], [TxMonitoringState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawalLog' : IDL.Func([], [IDL.Vec(WithdrawalLogEntry)], ['query']),
  'getWyomingCharter' : IDL.Func([], [WyomingState], ['query']),
  'initiateKyc' : IDL.Func([IDL.Text], [IDL.Text], []),
  'listBankAccounts' : IDL.Func([], [IDL.Vec(BankAccountEntry)], ['query']),
  'listBuilderDirectives' : IDL.Func(
      [],
      [IDL.Vec(BuilderDirective)],
      ['query'],
    ),
  'listEntities' : IDL.Func([], [IDL.Vec(BirthEntity)], ['query']),
  'listModelsByLayer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SovereignModel)],
      ['query'],
    ),
  'markOrganDegraded' : IDL.Func([IDL.Text], [], []),
  'markOrganUnreachable' : IDL.Func([IDL.Text], [], []),
  'px_getFullState' : IDL.Func([], [FullPxState], ['query']),
  'px_getNeurochemicals' : IDL.Func([], [IDL.Vec(IDL.Float64)], ['query']),
  'px_isGenesisActivated' : IDL.Func([], [IDL.Bool], ['query']),
  'recordBankTx' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerOrgan' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'routeBeat' : IDL.Func([IDL.Text, IDL.Nat], [ContextSlice], ['query']),
  'runFrntDemo' : IDL.Func([], [FrntDemo], []),
  'setBtcBalance' : IDL.Func([IDL.Float64], [], []),
  'setBtcPrice' : IDL.Func([IDL.Float64], [], []),
  'setCreatorPrincipal' : IDL.Func([], [IDL.Bool], []),
  'setEthBalance' : IDL.Func([IDL.Float64], [], []),
  'setEthPrice' : IDL.Func([IDL.Float64], [], []),
  'setGenesisLocked' : IDL.Func([IDL.Bool], [], []),
  'setIcpBalance' : IDL.Func([IDL.Float64], [], []),
  'setIcpPrice' : IDL.Func([IDL.Float64], [], []),
  'setKuramotoR' : IDL.Func([IDL.Float64], [], []),
  'setKycEndpoint' : IDL.Func([IDL.Text], [], []),
  'setUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBuilderDirective' : IDL.Func([IDL.Text], [IDL.Text], []),
  'tickBeatManual' : IDL.Func([], [IDL.Nat], []),
  'tickBeatManualGated' : IDL.Func(
      [],
      [IDL.Record({ 'beat' : IDL.Nat, 'gateOpen' : IDL.Bool })],
      [],
    ),
  'toggleDelegatedSigning' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateBankAccountRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateGrantStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateMilestone' : IDL.Func([IDL.Text, MilestoneStatus, IDL.Text], [], []),
  'updateNodeProvider' : IDL.Func([NodeProvider], [], []),
  'updateOrganHealth' : IDL.Func([HealthReport], [], []),
  'withdrawCreatorIcp' : IDL.Func([IDL.Float64], [IDL.Bool], []),
  'withdrawToExternalWallet' : IDL.Func(
      [IDL.Float64, IDL.Text],
      [
        IDL.Record({
          'error' : IDL.Opt(IDL.Text),
          'blockIndex' : IDL.Opt(IDL.Nat),
          'success' : IDL.Bool,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EdgeInput = IDL.Record({
    'relation' : IDL.Text,
    'toId' : IDL.Text,
    'fromId' : IDL.Text,
  });
  const Edge = IDL.Record({
    'id' : IDL.Text,
    'relation' : IDL.Text,
    'beat' : IDL.Nat,
    'toId' : IDL.Text,
    'fromId' : IDL.Text,
  });
  const GrantRecord = IDL.Record({
    'status' : IDL.Text,
    'grantType' : IDL.Text,
    'deadlineMs' : IDL.Int,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'amountUsd' : IDL.Nat,
  });
  const LessonTool = IDL.Record({
    'id' : IDL.Text,
    'publicAccess' : IDL.Bool,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'description' : IDL.Text,
    'teksCodes' : IDL.Vec(IDL.Text),
    'toolType' : IDL.Text,
  });
  const LedgerEntry = IDL.Record({
    'proofHash' : IDL.Text,
    'beat' : IDL.Nat,
    'phiDepth' : IDL.Nat,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'payload' : IDL.Text,
  });
  const NodeInput = IDL.Record({
    'labelText' : IDL.Text,
    'nodeType' : IDL.Text,
  });
  const Node = IDL.Record({
    'id' : IDL.Text,
    'beat' : IDL.Nat,
    'labelText' : IDL.Text,
    'nodeType' : IDL.Text,
  });
  const SchoolTier = IDL.Variant({
    'Gold' : IDL.Null,
    'Bronze' : IDL.Null,
    'Silver' : IDL.Null,
  });
  const SchoolRecord = IDL.Record({
    'id' : IDL.Text,
    'deployed' : IDL.Bool,
    'grantStatus' : IDL.Text,
    'name' : IDL.Text,
    'tier' : SchoolTier,
    'district' : IDL.Text,
    'contactEmail' : IDL.Text,
    'teksStandardsCodes' : IDL.Vec(IDL.Text),
    'canisterId' : IDL.Opt(IDL.Text),
  });
  const TeksStandard = IDL.Record({
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'code' : IDL.Text,
    'lessonTools' : IDL.Vec(LessonTool),
    'description' : IDL.Text,
    'grade' : IDL.Text,
  });
  const SovereignModel = IDL.Record({
    'id' : IDL.Text,
    'latinName' : IDL.Text,
    'meaning' : IDL.Text,
    'subIntelligence' : IDL.Text,
    'layer' : IDL.Text,
    'lastBeatActivated' : IDL.Int,
    'computation' : IDL.Text,
    'inputTypes' : IDL.Vec(IDL.Text),
    'microTokenId' : IDL.Nat32,
    'executionBinding' : IDL.Text,
    'maxMicroTokenOutput' : IDL.Nat,
    'beatActivationCount' : IDL.Nat,
  });
  const ProtocolRecordPublic = IDL.Record({
    'id' : IDL.Text,
    'principle' : IDL.Text,
    'executionCount' : IDL.Nat,
    'lastFiredBeat' : IDL.Int,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'lastResult' : IDL.Text,
    'equation' : IDL.Text,
    'precedence' : IDL.Nat,
  });
  const BankTxEntry = IDL.Record({
    'direction' : IDL.Variant({ 'in' : IDL.Null, 'out' : IDL.Null }),
    'asset' : IDL.Text,
    'note' : IDL.Text,
    'txId' : IDL.Text,
    'timestamp' : IDL.Nat,
    'amount' : IDL.Float64,
    'flagged' : IDL.Bool,
  });
  const BankAccountEntry = IDL.Record({
    'kycTimestamp' : IDL.Nat,
    'thresholdLimit' : IDL.Float64,
    'ownerName' : IDL.Text,
    'accountId' : IDL.Text,
    'delegatedSigning' : IDL.Bool,
    'createdAt' : IDL.Nat,
    'role' : IDL.Variant({
      'institutional' : IDL.Null,
      'personal' : IDL.Null,
      'business' : IDL.Null,
    }),
    'icpBalance' : IDL.Float64,
    'ckBtcBalance' : IDL.Float64,
    'kycStatus' : IDL.Variant({
      'notStarted' : IDL.Null,
      'verified' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'txHistory' : IDL.Vec(BankTxEntry),
    'ckEthBalance' : IDL.Float64,
  });
  const EntityType = IDL.Variant({
    'internal' : IDL.Null,
    'external' : IDL.Null,
  });
  const EntityState = IDL.Variant({
    'active' : IDL.Null,
    'transcended' : IDL.Null,
    'awakening' : IDL.Null,
    'dormant' : IDL.Null,
  });
  const BirthEntity = IDL.Record({
    'id' : IDL.Text,
    'organType' : IDL.Text,
    'directive' : IDL.Text,
    'birthBeat' : IDL.Int,
    'birthTimestamp' : IDL.Int,
    'name' : IDL.Text,
    'goalStack' : IDL.Vec(IDL.Text),
    'activation' : IDL.Float64,
    'entityType' : EntityType,
    'messageLog' : IDL.Vec(IDL.Text),
    'entityState' : EntityState,
  });
  const BirthAiState = IDL.Record({
    'lastBirthBeat' : IDL.Int,
    'totalTranscended' : IDL.Nat,
    'totalBorn' : IDL.Nat,
    'entities' : IDL.Vec(IDL.Tuple(IDL.Text, BirthEntity)),
  });
  const DirectiveStatus = IDL.Variant({
    'building' : IDL.Null,
    'complete' : IDL.Null,
    'failed' : IDL.Null,
    'parsed' : IDL.Null,
  });
  const TargetType = IDL.Variant({
    'protocol' : IDL.Null,
    'entity' : IDL.Null,
    'agent' : IDL.Null,
    'canister' : IDL.Null,
    'queryTarget' : IDL.Null,
  });
  const BuilderDirective = IDL.Record({
    'id' : IDL.Text,
    'status' : DirectiveStatus,
    'rawText' : IDL.Text,
    'parameters' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'parsedIntent' : IDL.Text,
    'timestamp' : IDL.Int,
    'targetType' : TargetType,
    'outputId' : IDL.Opt(IDL.Text),
  });
  const BuilderState = IDL.Record({
    'directives' : IDL.Vec(IDL.Tuple(IDL.Text, BuilderDirective)),
    'totalFailed' : IDL.Nat,
    'totalBuilt' : IDL.Nat,
  });
  const CardiacState = IDL.Record({
    'heartbeatActive' : IDL.Bool,
    'omnisFiredCount' : IDL.Nat,
    'hrvBound' : IDL.Float64,
    'coherenceDirection' : IDL.Int,
    'coherenceTarget' : IDL.Float64,
    'deoxygenationAlarms' : IDL.Nat,
    'lastBeatTime' : IDL.Int,
    'neurochemicalLevels' : IDL.Vec(IDL.Float64),
    'oxygenationScore' : IDL.Float64,
    'heartRate' : IDL.Float64,
    'globalCoherence' : IDL.Float64,
    'kuramotoR' : IDL.Float64,
    'strokeVolume' : IDL.Float64,
    'entanglaCarrier' : IDL.Float64,
    'lastOmnisFireBeat' : IDL.Nat,
  });
  const CodexEntry = IDL.Record({
    'id' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'numericalValue' : IDL.Float64,
    'enforcementAgi' : IDL.Text,
    'ancientSource' : IDL.Text,
    'principleOneLine' : IDL.Text,
    'computation' : IDL.Text,
    'category' : IDL.Text,
    'formula' : IDL.Text,
  });
  const ContextRouterState = IDL.Record({
    'totalBeatRoutes' : IDL.Nat,
    'microTokenBudgetPerBeat' : IDL.Nat,
    'avgResonanceScore' : IDL.Float64,
  });
  const CreatorReserveState = IDL.Record({
    'totalUsdEquiv' : IDL.Float64,
    'founderName' : IDL.Text,
    'withdrawableIcp' : IDL.Float64,
    'btcReserve' : IDL.Float64,
    'totalWithdrawn' : IDL.Float64,
    'icpReserve' : IDL.Float64,
    'mtcReserve' : IDL.Float64,
    'founderAccountId' : IDL.Text,
    'ethReserve' : IDL.Float64,
  });
  const DriveState = IDL.Record({
    'consecutiveDriveBeats' : IDL.Nat,
    'px_driveStrengths' : IDL.Vec(IDL.Float64),
    'dominantDriveId' : IDL.Nat,
  });
  const EngineState = IDL.Record({
    'jubileeCount' : IDL.Nat,
    'qbSuperradiance' : IDL.Float64,
    'shemaLastCheckBeat' : IDL.Nat,
    'anointedStateActive' : IDL.Bool,
    'axisCanisterId' : IDL.Text,
    'qbShell3Discharge' : IDL.Float64,
    'axisEagleElevation' : IDL.Float64,
    'qmemCanisterId' : IDL.Text,
    'fluxCanisterId' : IDL.Text,
    'jubileeLastBeat' : IDL.Nat,
    'resonexCanisterId' : IDL.Text,
    'kalmanConfidence' : IDL.Float64,
    'axisElephantDist' : IDL.Float64,
    'firePillarCount' : IDL.Nat,
    'firePillarActive' : IDL.Bool,
    'sevenSpiritsScore' : IDL.Float64,
    'axisEagleAccel' : IDL.Float64,
    'axisEagleCurvature' : IDL.Float64,
    'shemaIntegrityScore' : IDL.Float64,
    'prophetConvergenceCount' : IDL.Nat,
    'axisElephantRecall' : IDL.Float64,
    'prophetFunctionArmed' : IDL.Bool,
    'qbSuperchargeRate' : IDL.Float64,
  });
  const FormaState = IDL.Record({
    'spectralCoherence' : IDL.Float64,
    'projectionPlus10000' : IDL.Text,
    'beatCount' : IDL.Nat,
    'projectionPlus1000' : IDL.Text,
    'compoundRatePerBeat' : IDL.Float64,
    'capital' : IDL.Float64,
    'vonNeumannEntropy' : IDL.Float64,
  });
  const FullWalletSnapshot = IDL.Record({
    'totalUsdEquiv' : IDL.Float64,
    'creatorBtc' : IDL.Float64,
    'creatorEth' : IDL.Float64,
    'creatorIcp' : IDL.Float64,
    'creatorMtc' : IDL.Float64,
    'btcBalance' : IDL.Float64,
    'withdrawableIcp' : IDL.Float64,
    'beatCount' : IDL.Nat,
    'icpBalance' : IDL.Float64,
    'ethBalance' : IDL.Float64,
    'totalWithdrawn' : IDL.Float64,
    'tokenCount' : IDL.Nat,
    'mtcCirculating' : IDL.Float64,
    'neuronCount' : IDL.Nat,
  });
  const GenesisState = IDL.Record({
    'sl6Emission' : IDL.Float64,
    'genesisTimestamp' : IDL.Int,
    'sl2Resonance' : IDL.Float64,
    'beatCount' : IDL.Nat,
    'doctrineHash' : IDL.Text,
    'sl3Coherence' : IDL.Float64,
    'creatorName' : IDL.Text,
    'sl4Depth' : IDL.Float64,
    'creatorYear' : IDL.Nat,
    'alfredoLawActive' : IDL.Bool,
    'creatorJurisdiction' : IDL.Text,
    'sl7Depth' : IDL.Float64,
    'alfredoLawHash' : IDL.Text,
    'genesisLocked' : IDL.Bool,
    'sl5Amplitude' : IDL.Float64,
    'creatorTitle' : IDL.Text,
    'sl1Score' : IDL.Float64,
  });
  const GrantRecord_School = IDL.Record({
    'status' : IDL.Text,
    'deadlineMs' : IDL.Int,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'amountUsd' : IDL.Nat,
    'program' : IDL.Text,
  });
  const JacobRung = IDL.Record({
    'multiplier' : IDL.Float64,
    'rungNumber' : IDL.Nat,
    'labelText' : IDL.Text,
    'isCurrent' : IDL.Bool,
  });
  const JacobsLadderState = IDL.Record({
    'velocity' : IDL.Float64,
    'currentRung' : IDL.Nat,
    'saceciTarget' : IDL.Float64,
    'rungs' : IDL.Vec(JacobRung),
  });
  const KycRecord = IDL.Record({
    'status' : IDL.Variant({
      'notStarted' : IDL.Null,
      'verified' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'accountId' : IDL.Text,
    'retryCount' : IDL.Nat,
    'lastChecked' : IDL.Nat,
    'apiResponse' : IDL.Text,
  });
  const ModelRegistryState = IDL.Record({
    'lastActivated' : IDL.Text,
    'totalActivations' : IDL.Nat,
    'totalModels' : IDL.Nat,
    'microTokensConsumedTotal' : IDL.Nat,
  });
  const NeuronGroup = IDL.Record({
    'dissolveYears' : IDL.Float64,
    'count' : IDL.Nat,
    'fibIndex' : IDL.Nat,
    'groupId' : IDL.Text,
    'substrate' : IDL.Text,
    'purpose' : IDL.Text,
    'policy' : IDL.Text,
  });
  const NeuronFleetState = IDL.Record({
    'groups' : IDL.Vec(NeuronGroup),
    'fieldNodes' : IDL.Nat,
    'neuronsPerNode' : IDL.Nat,
    'totalNeurons' : IDL.Nat,
  });
  const NovaCognitiveLanguage = IDL.Record({
    'id' : IDL.Text,
    'latinName' : IDL.Text,
    'executionCount' : IDL.Nat,
    'coherenceGateScore' : IDL.Float64,
    'primaryObjects' : IDL.Vec(IDL.Text),
    'englishDomain' : IDL.Text,
    'runtimePhase' : IDL.Text,
    'lastBeatExecuted' : IDL.Int,
    'stack' : IDL.Text,
    'executionBinding' : IDL.Text,
  });
  const NovaRuntimeState = IDL.Record({
    'runtimePhase' : IDL.Text,
    'languages' : IDL.Vec(NovaCognitiveLanguage),
    'lastBeatExecuted' : IDL.Int,
    'totalExecutionCount' : IDL.Nat,
    'novaVersion' : IDL.Text,
  });
  const RegistryEntry = IDL.Record({
    'deployed' : IDL.Int,
    'organType' : IDL.Text,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'unreachable' : IDL.Null,
      'degraded' : IDL.Null,
    }),
    'messages' : IDL.Nat,
    'errors' : IDL.Nat,
    'latencyMs' : IDL.Int,
    'cycles' : IDL.Nat,
    'lastHeartbeat' : IDL.Int,
    'healthScore' : IDL.Float64,
    'principalId' : IDL.Opt(IDL.Principal),
    'canisterId' : IDL.Text,
  });
  const OrganismRecord = IDL.Record({
    'active' : IDL.Bool,
    'proofDepth' : IDL.Nat,
    'beat' : IDL.Nat,
    'name' : IDL.Text,
    'earnings' : IDL.Float64,
    'coherence' : IDL.Float64,
    'fieldType' : IDL.Nat,
    'canisterId' : IDL.Text,
  });
  const SubOrganismRecord = IDL.Record({
    'active' : IDL.Bool,
    'tier' : IDL.Nat,
    'parentId' : IDL.Text,
    'royaltyRate' : IDL.Float64,
    'canisterId' : IDL.Text,
  });
  const OrganismState = IDL.Record({
    'organisms' : IDL.Vec(OrganismRecord),
    'franchiseCutRate' : IDL.Float64,
    'franchiseCount' : IDL.Nat,
    'championPool' : IDL.Float64,
    'totalOrganismEarnings' : IDL.Float64,
    'activeCount' : IDL.Nat,
    'subOrganisms' : IDL.Vec(SubOrganismRecord),
  });
  const ProfitState = IDL.Record({
    'totalAllStreams' : IDL.Float64,
    'streams' : IDL.Vec(IDL.Float64),
  });
  const ProtocolCategory = IDL.Variant({
    'Law' : IDL.Null,
    'Reasoning' : IDL.Null,
    'Model' : IDL.Null,
    'Organ' : IDL.Null,
    'Behavior' : IDL.Null,
  });
  const ProtocolResult = IDL.Variant({
    'skipped' : IDL.Null,
    'failed' : IDL.Null,
    'passed' : IDL.Null,
  });
  const ProtocolRecord = IDL.Record({
    'id' : IDL.Text,
    'principle' : IDL.Text,
    'executionCount' : IDL.Nat,
    'lastFiredBeat' : IDL.Int,
    'name' : IDL.Text,
    'category' : ProtocolCategory,
    'lastResult' : ProtocolResult,
    'equation' : IDL.Text,
    'precedence' : IDL.Nat,
  });
  const ProtocolRegistry = IDL.Record({
    'totalExecutions' : IDL.Nat,
    'protocols' : IDL.Vec(IDL.Tuple(IDL.Text, ProtocolRecord)),
    'lastScanBeat' : IDL.Int,
  });
  const RegistryState = IDL.Record({
    'lastUpdated' : IDL.Int,
    'entries' : IDL.Vec(IDL.Tuple(IDL.Text, RegistryEntry)),
  });
  const SchoolRegistry = IDL.Record({
    'grants' : IDL.Vec(GrantRecord_School),
    'totalDeployed' : IDL.Nat,
    'schools' : IDL.Vec(SchoolRecord),
    'lastUpdatedMs' : IDL.Int,
    'teksStandards' : IDL.Vec(TeksStandard),
  });
  const ShellState = IDL.Record({
    'rValues' : IDL.Vec(IDL.Float64),
    'shell3Coherence' : IDL.Float64,
    'activations' : IDL.Vec(IDL.Float64),
    'shell3BeeGate' : IDL.Vec(IDL.Float64),
  });
  const SignalState = IDL.Record({
    'eagleSignal' : IDL.Float64,
    'orcaSignal' : IDL.Float64,
    'dolphinSignal' : IDL.Float64,
    'thyroidT3' : IDL.Float64,
    'thyroidT4' : IDL.Float64,
    'hiveSignal' : IDL.Float64,
    'crowSignal' : IDL.Float64,
    'wolfSignal' : IDL.Float64,
    'octopusSignal' : IDL.Float64,
    'respirationRate' : IDL.Float64,
    'heartRate' : IDL.Float64,
    'sharkSignal' : IDL.Float64,
    'cortisol' : IDL.Float64,
    'elephantSignal' : IDL.Float64,
  });
  const TokenEntry = IDL.Record({
    'homeCanister' : IDL.Text,
    'circulatingSupply' : IDL.Float64,
    'mintTrigger' : IDL.Text,
    'name' : IDL.Text,
    'managingAgi' : IDL.Text,
    'totalSupply' : IDL.Float64,
    'creatorReserveBalance' : IDL.Float64,
    'burnTrigger' : IDL.Text,
    'priceIcp' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TreasuryState = IDL.Record({
    'btcHardFloor' : IDL.Float64,
    'icpStaked' : IDL.Float64,
    'icpYieldRate' : IDL.Float64,
    'creatorMtcReserve' : IDL.Float64,
    'mtcPrice' : IDL.Float64,
    'creatorEthReserve' : IDL.Float64,
    'btcBalance' : IDL.Float64,
    'tokenBalances' : IDL.Vec(IDL.Float64),
    'clearanceReserves' : IDL.Vec(IDL.Float64),
    'creatorWithdrawableIcp' : IDL.Float64,
    'ethPrice' : IDL.Float64,
    'icpBalance' : IDL.Float64,
    'btcNetworkCongestion' : IDL.Float64,
    'ethRocketPoolRate' : IDL.Float64,
    'btcMempoolFeeRate' : IDL.Float64,
    'creatorTotalUsdEquiv' : IDL.Float64,
    'ethBalance' : IDL.Float64,
    'ethYieldRate' : IDL.Float64,
    'totalWithdrawn' : IDL.Float64,
    'btcPrice' : IDL.Float64,
    'icpPrice' : IDL.Float64,
    'icpAccruedYield' : IDL.Float64,
    'ethLidoRate' : IDL.Float64,
    'creatorBtcReserve' : IDL.Float64,
    'mtcBurned' : IDL.Float64,
    'mtcGenesisSupply' : IDL.Float64,
    'mtcCirculating' : IDL.Float64,
    'creatorIcpReserve' : IDL.Float64,
  });
  const TxMonitoringState = IDL.Record({
    'institutionalThreshold' : IDL.Float64,
    'totalMonitored' : IDL.Nat,
    'flaggedCount' : IDL.Nat,
    'lastFlaggedAt' : IDL.Nat,
    'personalThreshold' : IDL.Float64,
    'businessThreshold' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'principal' : IDL.Text, 'name' : IDL.Text });
  const WithdrawalLogEntry = IDL.Record({
    'error' : IDL.Opt(IDL.Text),
    'toPrincipal' : IDL.Text,
    'blockIndex' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
    'amount' : IDL.Float64,
  });
  const FrntDemo = IDL.Record({
    'visaFeeBps' : IDL.Nat,
    'demoActive' : IDL.Bool,
    'phantomFeeBps' : IDL.Nat,
    'visaBottleneckSolved' : IDL.Bool,
    'visaSettlementMs' : IDL.Nat,
    'lastRunMs' : IDL.Int,
    'phantomSettlementMs' : IDL.Nat,
  });
  const NodeProvider = IDL.Record({
    'entity' : IDL.Text,
    'status' : IDL.Text,
    'gen3Ready' : IDL.Bool,
    'bslWhitelisted' : IDL.Bool,
    'lincolnNodes' : IDL.Nat,
    'cheyenneNodes' : IDL.Nat,
    'targetRegion' : IDL.Text,
  });
  const MilestoneStatus = IDL.Variant({
    'Complete' : IDL.Null,
    'Critical' : IDL.Null,
    'InProgress' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Milestone = IDL.Record({
    'id' : IDL.Text,
    'status' : MilestoneStatus,
    'title' : IDL.Text,
    'deadlineMs' : IDL.Int,
    'notes' : IDL.Text,
  });
  const LegislativeTimeline = IDL.Record({
    'billReadyMs' : IDL.Int,
    'unicameralSession' : IDL.Text,
    'hardwareDeadlineMs' : IDL.Int,
    'milestones' : IDL.Vec(Milestone),
  });
  const Partnership = IDL.Record({
    'status' : IDL.Text,
    'contact' : IDL.Text,
    'partnerType' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Facility = IDL.Record({
    'publicPower' : IDL.Bool,
    'stateCode' : IDL.Text,
    'city' : IDL.Text,
    'internetBackbone' : IDL.Bool,
    'address' : IDL.Text,
    'powerCostRank' : IDL.Text,
    'vaultGrade' : IDL.Bool,
  });
  const WyomingState = IDL.Record({
    'charterGenesisHash' : IDL.Text,
    'grants' : IDL.Vec(GrantRecord),
    'frntDemo' : FrntDemo,
    'nodeProvider' : NodeProvider,
    'lastUpdatedMs' : IDL.Int,
    'legislative' : LegislativeTimeline,
    'partnerships' : IDL.Vec(Partnership),
    'facility' : Facility,
  });
  const FullPxState = IDL.Record({
    'regime' : IDL.Text,
    'jacobRung' : IDL.Nat,
    'beat' : IDL.Nat,
    'novaHealth' : IDL.Float64,
    'sacesiTarget' : IDL.Float64,
    'novelty' : IDL.Float64,
    'dominantDrive' : IDL.Text,
    'patentCount' : IDL.Nat,
    'aresArmed' : IDL.Bool,
    'lawScore' : IDL.Float64,
    'coherence' : IDL.Float64,
    'miningOutput' : IDL.Float64,
    'genesisActivated' : IDL.Bool,
    'formaCapital' : IDL.Float64,
    'mthBalance' : IDL.Float64,
    'gtkBalance' : IDL.Float64,
    'mrcBalance' : IDL.Float64,
  });
  const ContextSlice = IDL.Record({
    'microTokenBudget' : IDL.Nat,
    'resonanceScore' : IDL.Float64,
    'selectedModelIds' : IDL.Vec(IDL.Text),
    'microTokensUsed' : IDL.Nat,
    'beatTimestamp' : IDL.Int,
  });
  const HealthReport = IDL.Record({
    'organType' : IDL.Text,
    'messages' : IDL.Nat,
    'errors' : IDL.Nat,
    'latencyMs' : IDL.Int,
    'cycles' : IDL.Nat,
    'timestamp' : IDL.Int,
    'healthScore' : IDL.Float64,
  });
  
  return IDL.Service({
    'activateGenesis' : IDL.Func([IDL.Text], [IDL.Text], []),
    'addEdge' : IDL.Func([EdgeInput], [Edge], []),
    'addGrant' : IDL.Func([GrantRecord], [], []),
    'addLessonTool' : IDL.Func([IDL.Text, LessonTool], [], []),
    'addMessage' : IDL.Func([IDL.Text], [LedgerEntry], []),
    'addNode' : IDL.Func([NodeInput], [Node], []),
    'addSchool' : IDL.Func([SchoolRecord], [], []),
    'addTeksStandard' : IDL.Func([TeksStandard], [], []),
    'birthAI' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createBankAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deploySchoolCanister' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'entityLearn' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'entityRecall' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'entitySetGoal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'entitySpeak' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'executeBuilderDirective' : IDL.Func([IDL.Text], [IDL.Text], []),
    'executeNovaEngine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'exportFinCEN' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getAgiStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'memoria' : IDL.Record({
              'lex' : IDL.Text,
              'doctrineVerified' : IDL.Bool,
            }),
            'computator' : IDL.Record({
              'phi' : IDL.Float64,
              'fibonacciSeries' : IDL.Vec(IDL.Nat),
              'goldenAngle' : IDL.Float64,
              'schumannHz' : IDL.Float64,
            }),
            'gubernator' : IDL.Record({
              'voteCount' : IDL.Nat,
              'neuronGroups' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
            }),
            'custoditor' : IDL.Record({ 'reroutedNodes' : IDL.Vec(IDL.Text) }),
            'explorator' : IDL.Record({ 'topNodes' : IDL.Vec(IDL.Text) }),
            'liberator' : IDL.Record({
              'lastBlockIndex' : IDL.Opt(IDL.Nat),
              'totalWithdrawals' : IDL.Nat,
              'ready' : IDL.Bool,
            }),
            'dispensator' : IDL.Record({ 'totalDisbursed' : IDL.Float64 }),
          }),
        ],
        ['query'],
      ),
    'getAllModels' : IDL.Func([], [IDL.Vec(SovereignModel)], ['query']),
    'getAllProtocols' : IDL.Func(
        [],
        [IDL.Vec(ProtocolRecordPublic)],
        ['query'],
      ),
    'getAuditCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBankAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BankAccountEntry)],
        ['query'],
      ),
    'getBankingSsuState' : IDL.Func(
        [],
        [
          IDL.Record({
            'beatCount' : IDL.Nat,
            'kuramotoR' : IDL.Float64,
            'aegisStatus' : IDL.Text,
            'genesisHash' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getBankingYield' : IDL.Func(
        [],
        [
          IDL.Record({
            'weeklyEst' : IDL.Float64,
            'neuronGroupStatus' : IDL.Text,
            'dailyMaturityEst' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getBeatCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBirthAiState' : IDL.Func([], [BirthAiState], ['query']),
    'getBtcBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getBuilderState' : IDL.Func([], [BuilderState], ['query']),
    'getCardiacState' : IDL.Func([], [CardiacState], ['query']),
    'getCodexById' : IDL.Func([IDL.Text], [IDL.Opt(CodexEntry)], ['query']),
    'getCodexMathematicus' : IDL.Func([], [IDL.Vec(CodexEntry)], ['query']),
    'getContextRouterState' : IDL.Func([], [ContextRouterState], ['query']),
    'getCreatorPrincipalLocked' : IDL.Func([], [IDL.Bool], ['query']),
    'getCreatorReserve' : IDL.Func([], [CreatorReserveState], ['query']),
    'getCreatorWithdrawableIcp' : IDL.Func([], [IDL.Float64], ['query']),
    'getDomLibStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'verificatorChecks' : IDL.Nat,
            'confirmatorCount' : IDL.Nat,
            'auditorCount' : IDL.Nat,
            'protectorBlocks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDriveState' : IDL.Func([], [DriveState], ['query']),
    'getEdges' : IDL.Func([], [IDL.Vec(Edge)], ['query']),
    'getEngineState' : IDL.Func([], [EngineState], ['query']),
    'getEthBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getFlaggedTransactions' : IDL.Func([], [IDL.Vec(BankTxEntry)], ['query']),
    'getFormaState' : IDL.Func([], [FormaState], ['query']),
    'getFounderAccountId' : IDL.Func([], [IDL.Text], ['query']),
    'getFullWalletSnapshot' : IDL.Func([], [FullWalletSnapshot], ['query']),
    'getGenesisState' : IDL.Func([], [GenesisState], ['query']),
    'getGrantsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GrantRecord_School)],
        ['query'],
      ),
    'getIcpBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getJacobsLadder' : IDL.Func([], [JacobsLadderState], ['query']),
    'getKuramotoR' : IDL.Func([], [IDL.Float64], ['query']),
    'getKycEndpoint' : IDL.Func([], [IDL.Text], ['query']),
    'getKycStatus' : IDL.Func([IDL.Text], [IDL.Opt(KycRecord)], ['query']),
    'getLessonToolsByGrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LessonTool)],
        ['query'],
      ),
    'getLessonToolsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LessonTool)],
        ['query'],
      ),
    'getMemoriaNns' : IDL.Func(
        [],
        [IDL.Record({ 'lex' : IDL.Text, 'verified' : IDL.Bool })],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
    'getMicroTokenBudget' : IDL.Func([], [IDL.Nat], ['query']),
    'getModel' : IDL.Func([IDL.Text], [IDL.Opt(SovereignModel)], ['query']),
    'getModelCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getModelRegistryState' : IDL.Func([], [ModelRegistryState], ['query']),
    'getMtcCirculating' : IDL.Func([], [IDL.Float64], ['query']),
    'getNeuronFleet' : IDL.Func([], [NeuronFleetState], ['query']),
    'getNodes' : IDL.Func([], [IDL.Vec(Node)], ['query']),
    'getNovaActiveLanguages' : IDL.Func(
        [],
        [IDL.Vec(NovaCognitiveLanguage)],
        ['query'],
      ),
    'getNovaLanguageById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(NovaCognitiveLanguage)],
        ['query'],
      ),
    'getNovaLanguageRegistry' : IDL.Func(
        [],
        [IDL.Vec(NovaCognitiveLanguage)],
        ['query'],
      ),
    'getNovaLanguagesByStack' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NovaCognitiveLanguage)],
        ['query'],
      ),
    'getNovaRuntimeState' : IDL.Func([], [NovaRuntimeState], ['query']),
    'getOrganHealth' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RegistryEntry)],
        ['query'],
      ),
    'getOrganismState' : IDL.Func([], [OrganismState], ['query']),
    'getProfitState' : IDL.Func([], [ProfitState], ['query']),
    'getProtocolById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProtocolRecordPublic)],
        ['query'],
      ),
    'getProtocolLog' : IDL.Func([], [IDL.Vec(ProtocolRecordPublic)], ['query']),
    'getProtocolRegistry' : IDL.Func([], [ProtocolRegistry], ['query']),
    'getProtocolsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProtocolRecordPublic)],
        ['query'],
      ),
    'getPublicCurriculum' : IDL.Func([], [IDL.Vec(TeksStandard)], ['query']),
    'getRecentAudit' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
    'getRecentSettle' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
    'getRegistryCoherence' : IDL.Func([], [IDL.Float64], ['query']),
    'getRegistryEntries' : IDL.Func([], [IDL.Vec(RegistryEntry)], ['query']),
    'getRegistryState' : IDL.Func([], [RegistryState], ['query']),
    'getSchoolByDistrict' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SchoolRecord)],
        ['query'],
      ),
    'getSchoolRegistry' : IDL.Func([], [SchoolRegistry], ['query']),
    'getShellState' : IDL.Func([], [ShellState], ['query']),
    'getSignalState' : IDL.Func([], [SignalState], ['query']),
    'getTeksStandard' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TeksStandard)],
        ['query'],
      ),
    'getTokenBySymbol' : IDL.Func([IDL.Text], [IDL.Opt(TokenEntry)], ['query']),
    'getTokenRegistry' : IDL.Func([], [IDL.Vec(TokenEntry)], ['query']),
    'getTotalProfit' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalWithdrawn' : IDL.Func([], [IDL.Float64], ['query']),
    'getTreasuryState' : IDL.Func([], [TreasuryState], ['query']),
    'getTxMonitoringState' : IDL.Func([], [TxMonitoringState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawalLog' : IDL.Func([], [IDL.Vec(WithdrawalLogEntry)], ['query']),
    'getWyomingCharter' : IDL.Func([], [WyomingState], ['query']),
    'initiateKyc' : IDL.Func([IDL.Text], [IDL.Text], []),
    'listBankAccounts' : IDL.Func([], [IDL.Vec(BankAccountEntry)], ['query']),
    'listBuilderDirectives' : IDL.Func(
        [],
        [IDL.Vec(BuilderDirective)],
        ['query'],
      ),
    'listEntities' : IDL.Func([], [IDL.Vec(BirthEntity)], ['query']),
    'listModelsByLayer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SovereignModel)],
        ['query'],
      ),
    'markOrganDegraded' : IDL.Func([IDL.Text], [], []),
    'markOrganUnreachable' : IDL.Func([IDL.Text], [], []),
    'px_getFullState' : IDL.Func([], [FullPxState], ['query']),
    'px_getNeurochemicals' : IDL.Func([], [IDL.Vec(IDL.Float64)], ['query']),
    'px_isGenesisActivated' : IDL.Func([], [IDL.Bool], ['query']),
    'recordBankTx' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerOrgan' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'routeBeat' : IDL.Func([IDL.Text, IDL.Nat], [ContextSlice], ['query']),
    'runFrntDemo' : IDL.Func([], [FrntDemo], []),
    'setBtcBalance' : IDL.Func([IDL.Float64], [], []),
    'setBtcPrice' : IDL.Func([IDL.Float64], [], []),
    'setCreatorPrincipal' : IDL.Func([], [IDL.Bool], []),
    'setEthBalance' : IDL.Func([IDL.Float64], [], []),
    'setEthPrice' : IDL.Func([IDL.Float64], [], []),
    'setGenesisLocked' : IDL.Func([IDL.Bool], [], []),
    'setIcpBalance' : IDL.Func([IDL.Float64], [], []),
    'setIcpPrice' : IDL.Func([IDL.Float64], [], []),
    'setKuramotoR' : IDL.Func([IDL.Float64], [], []),
    'setKycEndpoint' : IDL.Func([IDL.Text], [], []),
    'setUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBuilderDirective' : IDL.Func([IDL.Text], [IDL.Text], []),
    'tickBeatManual' : IDL.Func([], [IDL.Nat], []),
    'tickBeatManualGated' : IDL.Func(
        [],
        [IDL.Record({ 'beat' : IDL.Nat, 'gateOpen' : IDL.Bool })],
        [],
      ),
    'toggleDelegatedSigning' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateBankAccountRole' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateGrantStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateMilestone' : IDL.Func([IDL.Text, MilestoneStatus, IDL.Text], [], []),
    'updateNodeProvider' : IDL.Func([NodeProvider], [], []),
    'updateOrganHealth' : IDL.Func([HealthReport], [], []),
    'withdrawCreatorIcp' : IDL.Func([IDL.Float64], [IDL.Bool], []),
    'withdrawToExternalWallet' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [
          IDL.Record({
            'error' : IDL.Opt(IDL.Text),
            'blockIndex' : IDL.Opt(IDL.Nat),
            'success' : IDL.Bool,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };