/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccountEntry {
  'kycTimestamp' : bigint,
  'thresholdLimit' : number,
  'ownerName' : string,
  'accountId' : string,
  'delegatedSigning' : boolean,
  'createdAt' : bigint,
  'role' : { 'institutional' : null } |
    { 'personal' : null } |
    { 'business' : null },
  'icpBalance' : number,
  'ckBtcBalance' : number,
  'kycStatus' : { 'notStarted' : null } |
    { 'verified' : null } |
    { 'pending' : null } |
    { 'rejected' : null },
  'txHistory' : Array<BankTxEntry>,
  'ckEthBalance' : number,
}
export interface BankTxEntry {
  'direction' : { 'in' : null } |
    { 'out' : null },
  'asset' : string,
  'note' : string,
  'txId' : string,
  'timestamp' : bigint,
  'amount' : number,
  'flagged' : boolean,
}
export interface BirthAiState {
  'lastBirthBeat' : bigint,
  'totalTranscended' : bigint,
  'totalBorn' : bigint,
  'entities' : Array<[string, BirthEntity]>,
}
export interface BirthEntity {
  'id' : string,
  'organType' : string,
  'directive' : string,
  'birthBeat' : bigint,
  'birthTimestamp' : bigint,
  'name' : string,
  'goalStack' : Array<string>,
  'activation' : number,
  'entityType' : EntityType,
  'messageLog' : Array<string>,
  'entityState' : EntityState,
}
export interface BuilderDirective {
  'id' : string,
  'status' : DirectiveStatus,
  'rawText' : string,
  'parameters' : Array<[string, string]>,
  'parsedIntent' : string,
  'timestamp' : bigint,
  'targetType' : TargetType,
  'outputId' : [] | [string],
}
export interface BuilderState {
  'directives' : Array<[string, BuilderDirective]>,
  'totalFailed' : bigint,
  'totalBuilt' : bigint,
}
export interface CardiacState {
  'heartbeatActive' : boolean,
  'omnisFiredCount' : bigint,
  'hrvBound' : number,
  'coherenceDirection' : bigint,
  'coherenceTarget' : number,
  'deoxygenationAlarms' : bigint,
  'lastBeatTime' : bigint,
  'neurochemicalLevels' : Array<number>,
  'oxygenationScore' : number,
  'heartRate' : number,
  'globalCoherence' : number,
  'kuramotoR' : number,
  'strokeVolume' : number,
  'entanglaCarrier' : number,
  'lastOmnisFireBeat' : bigint,
}
export interface CodexEntry {
  'id' : string,
  'meaning' : string,
  'name' : string,
  'numericalValue' : number,
  'enforcementAgi' : string,
  'ancientSource' : string,
  'principleOneLine' : string,
  'computation' : string,
  'category' : string,
  'formula' : string,
}
export interface ContextRouterState {
  'totalBeatRoutes' : bigint,
  'microTokenBudgetPerBeat' : bigint,
  'avgResonanceScore' : number,
}
export interface ContextSlice {
  'microTokenBudget' : bigint,
  'resonanceScore' : number,
  'selectedModelIds' : Array<string>,
  'microTokensUsed' : bigint,
  'beatTimestamp' : bigint,
}
export interface CreatorReserveState {
  'totalUsdEquiv' : number,
  'founderName' : string,
  'withdrawableIcp' : number,
  'btcReserve' : number,
  'totalWithdrawn' : number,
  'icpReserve' : number,
  'mtcReserve' : number,
  'founderAccountId' : string,
  'ethReserve' : number,
}
export type DirectiveStatus = { 'building' : null } |
  { 'complete' : null } |
  { 'failed' : null } |
  { 'parsed' : null };
export interface DriveState {
  'consecutiveDriveBeats' : bigint,
  'px_driveStrengths' : Array<number>,
  'dominantDriveId' : bigint,
}
export interface Edge {
  'id' : string,
  'relation' : string,
  'beat' : bigint,
  'toId' : string,
  'fromId' : string,
}
export interface EdgeInput {
  'relation' : string,
  'toId' : string,
  'fromId' : string,
}
export interface EngineState {
  'jubileeCount' : bigint,
  'qbSuperradiance' : number,
  'shemaLastCheckBeat' : bigint,
  'anointedStateActive' : boolean,
  'axisCanisterId' : string,
  'qbShell3Discharge' : number,
  'axisEagleElevation' : number,
  'qmemCanisterId' : string,
  'fluxCanisterId' : string,
  'jubileeLastBeat' : bigint,
  'resonexCanisterId' : string,
  'kalmanConfidence' : number,
  'axisElephantDist' : number,
  'firePillarCount' : bigint,
  'firePillarActive' : boolean,
  'sevenSpiritsScore' : number,
  'axisEagleAccel' : number,
  'axisEagleCurvature' : number,
  'shemaIntegrityScore' : number,
  'prophetConvergenceCount' : bigint,
  'axisElephantRecall' : number,
  'prophetFunctionArmed' : boolean,
  'qbSuperchargeRate' : number,
}
export type EntityState = { 'active' : null } |
  { 'transcended' : null } |
  { 'awakening' : null } |
  { 'dormant' : null };
export type EntityType = { 'internal' : null } |
  { 'external' : null };
export interface Facility {
  'publicPower' : boolean,
  'stateCode' : string,
  'city' : string,
  'internetBackbone' : boolean,
  'address' : string,
  'powerCostRank' : string,
  'vaultGrade' : boolean,
}
export interface FormaState {
  'spectralCoherence' : number,
  'projectionPlus10000' : string,
  'beatCount' : bigint,
  'projectionPlus1000' : string,
  'compoundRatePerBeat' : number,
  'capital' : number,
  'vonNeumannEntropy' : number,
}
export interface FrntDemo {
  'visaFeeBps' : bigint,
  'demoActive' : boolean,
  'phantomFeeBps' : bigint,
  'visaBottleneckSolved' : boolean,
  'visaSettlementMs' : bigint,
  'lastRunMs' : bigint,
  'phantomSettlementMs' : bigint,
}
export interface FullPxState {
  'regime' : string,
  'jacobRung' : bigint,
  'beat' : bigint,
  'novaHealth' : number,
  'sacesiTarget' : number,
  'novelty' : number,
  'dominantDrive' : string,
  'patentCount' : bigint,
  'aresArmed' : boolean,
  'lawScore' : number,
  'coherence' : number,
  'miningOutput' : number,
  'genesisActivated' : boolean,
  'formaCapital' : number,
  'mthBalance' : number,
  'gtkBalance' : number,
  'mrcBalance' : number,
}
export interface FullWalletSnapshot {
  'totalUsdEquiv' : number,
  'creatorBtc' : number,
  'creatorEth' : number,
  'creatorIcp' : number,
  'creatorMtc' : number,
  'btcBalance' : number,
  'withdrawableIcp' : number,
  'beatCount' : bigint,
  'icpBalance' : number,
  'ethBalance' : number,
  'totalWithdrawn' : number,
  'tokenCount' : bigint,
  'mtcCirculating' : number,
  'neuronCount' : bigint,
}
export interface GenesisState {
  'sl6Emission' : number,
  'genesisTimestamp' : bigint,
  'sl2Resonance' : number,
  'beatCount' : bigint,
  'doctrineHash' : string,
  'sl3Coherence' : number,
  'creatorName' : string,
  'sl4Depth' : number,
  'creatorYear' : bigint,
  'alfredoLawActive' : boolean,
  'creatorJurisdiction' : string,
  'sl7Depth' : number,
  'alfredoLawHash' : string,
  'genesisLocked' : boolean,
  'sl5Amplitude' : number,
  'creatorTitle' : string,
  'sl1Score' : number,
}
export interface GrantRecord {
  'status' : string,
  'grantType' : string,
  'deadlineMs' : bigint,
  'name' : string,
  'notes' : string,
  'amountUsd' : bigint,
}
export interface GrantRecord_School {
  'status' : string,
  'deadlineMs' : bigint,
  'name' : string,
  'notes' : string,
  'amountUsd' : bigint,
  'program' : string,
}
export interface HealthReport {
  'organType' : string,
  'messages' : bigint,
  'errors' : bigint,
  'latencyMs' : bigint,
  'cycles' : bigint,
  'timestamp' : bigint,
  'healthScore' : number,
}
export interface JacobRung {
  'multiplier' : number,
  'rungNumber' : bigint,
  'labelText' : string,
  'isCurrent' : boolean,
}
export interface JacobsLadderState {
  'velocity' : number,
  'currentRung' : bigint,
  'saceciTarget' : number,
  'rungs' : Array<JacobRung>,
}
export interface KycRecord {
  'status' : { 'notStarted' : null } |
    { 'verified' : null } |
    { 'pending' : null } |
    { 'rejected' : null },
  'accountId' : string,
  'retryCount' : bigint,
  'lastChecked' : bigint,
  'apiResponse' : string,
}
export interface LedgerEntry {
  'proofHash' : string,
  'beat' : bigint,
  'phiDepth' : bigint,
  'timestamp' : bigint,
  'category' : string,
  'payload' : string,
}
export interface LegislativeTimeline {
  'billReadyMs' : bigint,
  'unicameralSession' : string,
  'hardwareDeadlineMs' : bigint,
  'milestones' : Array<Milestone>,
}
export interface LessonTool {
  'id' : string,
  'publicAccess' : boolean,
  'title' : string,
  'subject' : string,
  'description' : string,
  'teksCodes' : Array<string>,
  'toolType' : string,
}
export interface Milestone {
  'id' : string,
  'status' : MilestoneStatus,
  'title' : string,
  'deadlineMs' : bigint,
  'notes' : string,
}
export type MilestoneStatus = { 'Complete' : null } |
  { 'Critical' : null } |
  { 'InProgress' : null } |
  { 'Pending' : null };
export interface ModelRegistryState {
  'lastActivated' : string,
  'totalActivations' : bigint,
  'totalModels' : bigint,
  'microTokensConsumedTotal' : bigint,
}
export interface NeuronFleetState {
  'groups' : Array<NeuronGroup>,
  'fieldNodes' : bigint,
  'neuronsPerNode' : bigint,
  'totalNeurons' : bigint,
}
export interface NeuronGroup {
  'dissolveYears' : number,
  'count' : bigint,
  'fibIndex' : bigint,
  'groupId' : string,
  'substrate' : string,
  'purpose' : string,
  'policy' : string,
}
export interface Node {
  'id' : string,
  'beat' : bigint,
  'labelText' : string,
  'nodeType' : string,
}
export interface NodeInput { 'labelText' : string, 'nodeType' : string }
export interface NodeProvider {
  'entity' : string,
  'status' : string,
  'gen3Ready' : boolean,
  'bslWhitelisted' : boolean,
  'lincolnNodes' : bigint,
  'cheyenneNodes' : bigint,
  'targetRegion' : string,
}
export interface NovaCognitiveLanguage {
  'id' : string,
  'latinName' : string,
  'executionCount' : bigint,
  'coherenceGateScore' : number,
  'primaryObjects' : Array<string>,
  'englishDomain' : string,
  'runtimePhase' : string,
  'lastBeatExecuted' : bigint,
  'stack' : string,
  'executionBinding' : string,
}
export interface NovaRuntimeState {
  'runtimePhase' : string,
  'languages' : Array<NovaCognitiveLanguage>,
  'lastBeatExecuted' : bigint,
  'totalExecutionCount' : bigint,
  'novaVersion' : string,
}
export interface OrganismRecord {
  'active' : boolean,
  'proofDepth' : bigint,
  'beat' : bigint,
  'name' : string,
  'earnings' : number,
  'coherence' : number,
  'fieldType' : bigint,
  'canisterId' : string,
}
export interface OrganismState {
  'organisms' : Array<OrganismRecord>,
  'franchiseCutRate' : number,
  'franchiseCount' : bigint,
  'championPool' : number,
  'totalOrganismEarnings' : number,
  'activeCount' : bigint,
  'subOrganisms' : Array<SubOrganismRecord>,
}
export interface Partnership {
  'status' : string,
  'contact' : string,
  'partnerType' : string,
  'name' : string,
  'notes' : string,
}
export interface ProfitState {
  'totalAllStreams' : number,
  'streams' : Array<number>,
}
export type ProtocolCategory = { 'Law' : null } |
  { 'Reasoning' : null } |
  { 'Model' : null } |
  { 'Organ' : null } |
  { 'Behavior' : null };
export interface ProtocolRecord {
  'id' : string,
  'principle' : string,
  'executionCount' : bigint,
  'lastFiredBeat' : bigint,
  'name' : string,
  'category' : ProtocolCategory,
  'lastResult' : ProtocolResult,
  'equation' : string,
  'precedence' : bigint,
}
export interface ProtocolRecordPublic {
  'id' : string,
  'principle' : string,
  'executionCount' : bigint,
  'lastFiredBeat' : bigint,
  'name' : string,
  'category' : string,
  'lastResult' : string,
  'equation' : string,
  'precedence' : bigint,
}
export interface ProtocolRegistry {
  'totalExecutions' : bigint,
  'protocols' : Array<[string, ProtocolRecord]>,
  'lastScanBeat' : bigint,
}
export type ProtocolResult = { 'skipped' : null } |
  { 'failed' : null } |
  { 'passed' : null };
export interface RegistryEntry {
  'deployed' : bigint,
  'organType' : string,
  'status' : { 'active' : null } |
    { 'unreachable' : null } |
    { 'degraded' : null },
  'messages' : bigint,
  'errors' : bigint,
  'latencyMs' : bigint,
  'cycles' : bigint,
  'lastHeartbeat' : bigint,
  'healthScore' : number,
  'principalId' : [] | [Principal],
  'canisterId' : string,
}
export interface RegistryState {
  'lastUpdated' : bigint,
  'entries' : Array<[string, RegistryEntry]>,
}
export interface SchoolRecord {
  'id' : string,
  'deployed' : boolean,
  'grantStatus' : string,
  'name' : string,
  'tier' : SchoolTier,
  'district' : string,
  'contactEmail' : string,
  'teksStandardsCodes' : Array<string>,
  'canisterId' : [] | [string],
}
export interface SchoolRegistry {
  'grants' : Array<GrantRecord_School>,
  'totalDeployed' : bigint,
  'schools' : Array<SchoolRecord>,
  'lastUpdatedMs' : bigint,
  'teksStandards' : Array<TeksStandard>,
}
export type SchoolTier = { 'Gold' : null } |
  { 'Bronze' : null } |
  { 'Silver' : null };
export interface ShellState {
  'rValues' : Array<number>,
  'shell3Coherence' : number,
  'activations' : Array<number>,
  'shell3BeeGate' : Array<number>,
}
export interface SignalState {
  'eagleSignal' : number,
  'orcaSignal' : number,
  'dolphinSignal' : number,
  'thyroidT3' : number,
  'thyroidT4' : number,
  'hiveSignal' : number,
  'crowSignal' : number,
  'wolfSignal' : number,
  'octopusSignal' : number,
  'respirationRate' : number,
  'heartRate' : number,
  'sharkSignal' : number,
  'cortisol' : number,
  'elephantSignal' : number,
}
export interface SovereignModel {
  'id' : string,
  'latinName' : string,
  'meaning' : string,
  'subIntelligence' : string,
  'layer' : string,
  'lastBeatActivated' : bigint,
  'computation' : string,
  'inputTypes' : Array<string>,
  'microTokenId' : number,
  'executionBinding' : string,
  'maxMicroTokenOutput' : bigint,
  'beatActivationCount' : bigint,
}
export interface SubOrganismRecord {
  'active' : boolean,
  'tier' : bigint,
  'parentId' : string,
  'royaltyRate' : number,
  'canisterId' : string,
}
export type TargetType = { 'protocol' : null } |
  { 'entity' : null } |
  { 'agent' : null } |
  { 'canister' : null } |
  { 'queryTarget' : null };
export interface TeksStandard {
  'title' : string,
  'subject' : string,
  'code' : string,
  'lessonTools' : Array<LessonTool>,
  'description' : string,
  'grade' : string,
}
export interface TokenEntry {
  'homeCanister' : string,
  'circulatingSupply' : number,
  'mintTrigger' : string,
  'name' : string,
  'managingAgi' : string,
  'totalSupply' : number,
  'creatorReserveBalance' : number,
  'burnTrigger' : string,
  'priceIcp' : number,
  'symbol' : string,
}
export interface TreasuryState {
  'btcHardFloor' : number,
  'icpStaked' : number,
  'icpYieldRate' : number,
  'creatorMtcReserve' : number,
  'mtcPrice' : number,
  'creatorEthReserve' : number,
  'btcBalance' : number,
  'tokenBalances' : Array<number>,
  'clearanceReserves' : Array<number>,
  'creatorWithdrawableIcp' : number,
  'ethPrice' : number,
  'icpBalance' : number,
  'btcNetworkCongestion' : number,
  'ethRocketPoolRate' : number,
  'btcMempoolFeeRate' : number,
  'creatorTotalUsdEquiv' : number,
  'ethBalance' : number,
  'ethYieldRate' : number,
  'totalWithdrawn' : number,
  'btcPrice' : number,
  'icpPrice' : number,
  'icpAccruedYield' : number,
  'ethLidoRate' : number,
  'creatorBtcReserve' : number,
  'mtcBurned' : number,
  'mtcGenesisSupply' : number,
  'mtcCirculating' : number,
  'creatorIcpReserve' : number,
}
export interface TxMonitoringState {
  'institutionalThreshold' : number,
  'totalMonitored' : bigint,
  'flaggedCount' : bigint,
  'lastFlaggedAt' : bigint,
  'personalThreshold' : number,
  'businessThreshold' : number,
}
export interface UserProfile { 'principal' : string, 'name' : string }
export interface WithdrawalLogEntry {
  'error' : [] | [string],
  'toPrincipal' : string,
  'blockIndex' : [] | [bigint],
  'timestamp' : bigint,
  'success' : boolean,
  'amount' : number,
}
export interface WyomingState {
  'charterGenesisHash' : string,
  'grants' : Array<GrantRecord>,
  'frntDemo' : FrntDemo,
  'nodeProvider' : NodeProvider,
  'lastUpdatedMs' : bigint,
  'legislative' : LegislativeTimeline,
  'partnerships' : Array<Partnership>,
  'facility' : Facility,
}
export interface _SERVICE {
  /**
   * / activateGenesis — inscribe the founding word permanently
   * / Calls genesis_activation.activateGenesis(), persists result in genesisInternalState.
   * / Also sets genesisLocked in SovereignDB so the activation flag mirrors in main db.
   */
  'activateGenesis' : ActorMethod<[string], string>,
  'addEdge' : ActorMethod<[EdgeInput], Edge>,
  /**
   * / addGrant — creator-only
   * / Appends a new grant record to the Wyoming charter
   */
  'addGrant' : ActorMethod<[GrantRecord], undefined>,
  'addLessonTool' : ActorMethod<[string, LessonTool], undefined>,
  'addMessage' : ActorMethod<[string], LedgerEntry>,
  'addNode' : ActorMethod<[NodeInput], Node>,
  'addSchool' : ActorMethod<[SchoolRecord], undefined>,
  'addTeksStandard' : ActorMethod<[TeksStandard], undefined>,
  /**
   * / birthAI — create a sovereign entity or external agent
   * / entityType: "internal" (born into organism) | "external" (operates outside)
   * / directive: plain natural language — organ type auto-classified from keywords
   * / Returns the new entityId
   */
  'birthAI' : ActorMethod<[string, string, string], string>,
  'createBankAccount' : ActorMethod<[string, string, string], string>,
  'deploySchoolCanister' : ActorMethod<[string, string], undefined>,
  /**
   * / entityLearn — increase entity activation by phi^-1 per call; caps at 1.0
   * / PHI LAW: activation compounds at the golden ratio inverse — phi-derived growth
   */
  'entityLearn' : ActorMethod<[string, string], undefined>,
  /**
   * / entityRecall — search entity message log for past messages matching query
   */
  'entityRecall' : ActorMethod<[string, string], Array<string>>,
  /**
   * / entitySetGoal — push a goal onto the entity's goal stack (max 10)
   */
  'entitySetGoal' : ActorMethod<[string, string], undefined>,
  /**
   * / entitySpeak — send a message to a sovereign entity, receive its response
   */
  'entitySpeak' : ActorMethod<[string, string], string>,
  /**
   * / executeBuilderDirective — execute a previously parsed directive
   * / If targetType is entity/agent → calls birthAI internally
   * / Returns execution result string
   */
  'executeBuilderDirective' : ActorMethod<[string], string>,
  /**
   * / executeNovaEngine — dispatch a specific cognitive language engine by ID
   * / Returns execution result. Coherence gate enforced: R >= 0.618 required.
   */
  'executeNovaEngine' : ActorMethod<[string, string], string>,
  'exportFinCEN' : ActorMethod<[string], string>,
  'getAgiStatus' : ActorMethod<
    [],
    {
      'memoria' : { 'lex' : string, 'doctrineVerified' : boolean },
      'computator' : {
        'phi' : number,
        'fibonacciSeries' : Array<bigint>,
        'goldenAngle' : number,
        'schumannHz' : number,
      },
      'gubernator' : {
        'voteCount' : bigint,
        'neuronGroups' : Array<[string, bigint]>,
      },
      'custoditor' : { 'reroutedNodes' : Array<string> },
      'explorator' : { 'topNodes' : Array<string> },
      'liberator' : {
        'lastBlockIndex' : [] | [bigint],
        'totalWithdrawals' : bigint,
        'ready' : boolean,
      },
      'dispensator' : { 'totalDisbursed' : number },
    }
  >,
  /**
   * / getAllModels — return all 300 sovereign models
   */
  'getAllModels' : ActorMethod<[], Array<SovereignModel>>,
  /**
   * / getAllProtocols — all 89+ protocol records as public-safe array
   */
  'getAllProtocols' : ActorMethod<[], Array<ProtocolRecordPublic>>,
  'getAuditCount' : ActorMethod<[], bigint>,
  'getBankAccount' : ActorMethod<[string], [] | [BankAccountEntry]>,
  'getBankingSsuState' : ActorMethod<
    [],
    {
      'beatCount' : bigint,
      'kuramotoR' : number,
      'aegisStatus' : string,
      'genesisHash' : string,
    }
  >,
  'getBankingYield' : ActorMethod<
    [],
    {
      'weeklyEst' : number,
      'neuronGroupStatus' : string,
      'dailyMaturityEst' : number,
    }
  >,
  'getBeatCount' : ActorMethod<[], bigint>,
  /**
   * / getBirthAiState — full BirthAI domain snapshot
   */
  'getBirthAiState' : ActorMethod<[], BirthAiState>,
  'getBtcBalance' : ActorMethod<[], number>,
  /**
   * / getBuilderState — full Builder SDK domain snapshot
   */
  'getBuilderState' : ActorMethod<[], BuilderState>,
  'getCardiacState' : ActorMethod<[], CardiacState>,
  'getCodexById' : ActorMethod<[string], [] | [CodexEntry]>,
  'getCodexMathematicus' : ActorMethod<[], Array<CodexEntry>>,
  /**
   * / getContextRouterState — aggregate context router stats
   */
  'getContextRouterState' : ActorMethod<[], ContextRouterState>,
  'getCreatorPrincipalLocked' : ActorMethod<[], boolean>,
  'getCreatorReserve' : ActorMethod<[], CreatorReserveState>,
  'getCreatorWithdrawableIcp' : ActorMethod<[], number>,
  'getDomLibStatus' : ActorMethod<
    [],
    {
      'verificatorChecks' : bigint,
      'confirmatorCount' : bigint,
      'auditorCount' : bigint,
      'protectorBlocks' : bigint,
    }
  >,
  'getDriveState' : ActorMethod<[], DriveState>,
  'getEdges' : ActorMethod<[], Array<Edge>>,
  'getEngineState' : ActorMethod<[], EngineState>,
  'getEthBalance' : ActorMethod<[], number>,
  'getFlaggedTransactions' : ActorMethod<[], Array<BankTxEntry>>,
  'getFormaState' : ActorMethod<[], FormaState>,
  /**
   * / getFounderAccountId — returns the canonical sovereign ICP account ID permanently wired
   * / Address: 8c047c715f630bb8824c4831a1b95ad181a4b9264c528131fd5eccc2e4c6b879
   * / All D_LIQUID disbursements and LIBERATOR withdrawals route to this address by default.
   */
  'getFounderAccountId' : ActorMethod<[], string>,
  'getFullWalletSnapshot' : ActorMethod<[], FullWalletSnapshot>,
  'getGenesisState' : ActorMethod<[], GenesisState>,
  'getGrantsByStatus' : ActorMethod<[string], Array<GrantRecord_School>>,
  'getIcpBalance' : ActorMethod<[], number>,
  'getJacobsLadder' : ActorMethod<[], JacobsLadderState>,
  'getKuramotoR' : ActorMethod<[], number>,
  'getKycEndpoint' : ActorMethod<[], string>,
  'getKycStatus' : ActorMethod<[string], [] | [KycRecord]>,
  'getLessonToolsByGrade' : ActorMethod<[string], Array<LessonTool>>,
  'getLessonToolsBySubject' : ActorMethod<[string], Array<LessonTool>>,
  'getMemoriaNns' : ActorMethod<[], { 'lex' : string, 'verified' : boolean }>,
  'getMessages' : ActorMethod<[bigint], Array<LedgerEntry>>,
  /**
   * / getMicroTokenBudget — returns the per-beat micro-token budget (200_000)
   */
  'getMicroTokenBudget' : ActorMethod<[], bigint>,
  /**
   * / getModel — retrieve a sovereign model by ID (e.g., "M-001")
   */
  'getModel' : ActorMethod<[string], [] | [SovereignModel]>,
  /**
   * / getModelCount — always returns 300
   */
  'getModelCount' : ActorMethod<[], bigint>,
  /**
   * / getModelRegistryState — aggregate model registry stats
   */
  'getModelRegistryState' : ActorMethod<[], ModelRegistryState>,
  'getMtcCirculating' : ActorMethod<[], number>,
  'getNeuronFleet' : ActorMethod<[], NeuronFleetState>,
  'getNodes' : ActorMethod<[], Array<Node>>,
  /**
   * / getNovaActiveLanguages — engines currently in active or transcended phase
   */
  'getNovaActiveLanguages' : ActorMethod<[], Array<NovaCognitiveLanguage>>,
  /**
   * / getNovaLanguageById — retrieve one engine record by ID
   */
  'getNovaLanguageById' : ActorMethod<[string], [] | [NovaCognitiveLanguage]>,
  /**
   * / getNovaLanguageRegistry — all 40 cognitive language engine records
   */
  'getNovaLanguageRegistry' : ActorMethod<[], Array<NovaCognitiveLanguage>>,
  /**
   * / getNovaLanguagesByStack — retrieve all engines in a named stack
   */
  'getNovaLanguagesByStack' : ActorMethod<
    [string],
    Array<NovaCognitiveLanguage>
  >,
  /**
   * / getNovaRuntimeState — full NOVA runtime state snapshot
   */
  'getNovaRuntimeState' : ActorMethod<[], NovaRuntimeState>,
  /**
   * / getOrganHealth — health record for a specific organ type
   */
  'getOrganHealth' : ActorMethod<[string], [] | [RegistryEntry]>,
  'getOrganismState' : ActorMethod<[], OrganismState>,
  'getProfitState' : ActorMethod<[], ProfitState>,
  /**
   * / getProtocolById — lookup one protocol record by ID (e.g., "L01", "M05", "B03")
   */
  'getProtocolById' : ActorMethod<[string], [] | [ProtocolRecordPublic]>,
  /**
   * / getProtocolLog — all protocols sorted by lastFiredBeat descending
   */
  'getProtocolLog' : ActorMethod<[], Array<ProtocolRecordPublic>>,
  /**
   * / getProtocolRegistry — full protocol execution registry snapshot
   */
  'getProtocolRegistry' : ActorMethod<[], ProtocolRegistry>,
  /**
   * / getProtocolsByCategory — all protocols of a given category
   * / category: "Law" | "Model" | "Behavior" | "Reasoning" | "Organ"
   */
  'getProtocolsByCategory' : ActorMethod<[string], Array<ProtocolRecordPublic>>,
  'getPublicCurriculum' : ActorMethod<[], Array<TeksStandard>>,
  'getRecentAudit' : ActorMethod<[bigint], Array<LedgerEntry>>,
  'getRecentSettle' : ActorMethod<[bigint], Array<LedgerEntry>>,
  /**
   * / getRegistryCoherence — mean healthScore across all registered organs
   */
  'getRegistryCoherence' : ActorMethod<[], number>,
  /**
   * / getRegistryEntries — all registered organ entries as a flat array
   */
  'getRegistryEntries' : ActorMethod<[], Array<RegistryEntry>>,
  /**
   * / getRegistryState — full canister registry snapshot (all 9 organs)
   */
  'getRegistryState' : ActorMethod<[], RegistryState>,
  'getSchoolByDistrict' : ActorMethod<[string], Array<SchoolRecord>>,
  'getSchoolRegistry' : ActorMethod<[], SchoolRegistry>,
  'getShellState' : ActorMethod<[], ShellState>,
  'getSignalState' : ActorMethod<[], SignalState>,
  'getTeksStandard' : ActorMethod<[string], [] | [TeksStandard]>,
  'getTokenBySymbol' : ActorMethod<[string], [] | [TokenEntry]>,
  'getTokenRegistry' : ActorMethod<[], Array<TokenEntry>>,
  'getTotalProfit' : ActorMethod<[], number>,
  'getTotalWithdrawn' : ActorMethod<[], number>,
  'getTreasuryState' : ActorMethod<[], TreasuryState>,
  'getTxMonitoringState' : ActorMethod<[], TxMonitoringState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWithdrawalLog' : ActorMethod<[], Array<WithdrawalLogEntry>>,
  /**
   * / getWyomingCharter — public query, no auth required
   * / Returns the full sovereign Wyoming charter state
   */
  'getWyomingCharter' : ActorMethod<[], WyomingState>,
  'initiateKyc' : ActorMethod<[string], string>,
  'listBankAccounts' : ActorMethod<[], Array<BankAccountEntry>>,
  /**
   * / listBuilderDirectives — return all submitted directives
   */
  'listBuilderDirectives' : ActorMethod<[], Array<BuilderDirective>>,
  /**
   * / listEntities — return all sovereign entities (internal + external)
   */
  'listEntities' : ActorMethod<[], Array<BirthEntity>>,
  /**
   * / listModelsByLayer — return all models in a given layer ("MICRO" | "MESO" | "MACRO")
   */
  'listModelsByLayer' : ActorMethod<[string], Array<SovereignModel>>,
  /**
   * / markOrganDegraded — creator-only: force organ status to #degraded
   */
  'markOrganDegraded' : ActorMethod<[string], undefined>,
  /**
   * / markOrganUnreachable — creator-only: force organ status to #unreachable
   */
  'markOrganUnreachable' : ActorMethod<[string], undefined>,
  /**
   * / px_getFullState — single-call sovereign organism snapshot
   * / Wired to real SovereignDB domain state — no hardcoded numbers
   */
  'px_getFullState' : ActorMethod<[], FullPxState>,
  /**
   * / px_getNeurochemicals — returns the 18 neurochemical Float levels from CardiacState
   * / Pads with 0.0 if fewer than 18 values exist
   */
  'px_getNeurochemicals' : ActorMethod<[], Array<number>>,
  /**
   * / px_isGenesisActivated — returns true when the founding word has been inscribed
   * / Reads GenesisInternalState (activation record) and falls back to genesisLocked flag
   */
  'px_isGenesisActivated' : ActorMethod<[], boolean>,
  'recordBankTx' : ActorMethod<
    [string, number, string, string, string],
    string
  >,
  /**
   * / registerOrgan — creator-only: wire a deployed organ canister ID
   */
  'registerOrgan' : ActorMethod<[string, string], undefined>,
  /**
   * / routeBeat — route a beat signal text to top-K resonant models
   */
  'routeBeat' : ActorMethod<[string, bigint], ContextSlice>,
  /**
   * / runFrntDemo — Ω_GATE: Kuramoto R must be >= 0.618 (phi^-1)
   * / Executes the FRNT settlement demo, records the run timestamp
   * / Proves: 0.3s (Phantom) vs 900s (Visa), 0% vs 4% fee
   */
  'runFrntDemo' : ActorMethod<[], FrntDemo>,
  'setBtcBalance' : ActorMethod<[number], undefined>,
  'setBtcPrice' : ActorMethod<[number], undefined>,
  'setCreatorPrincipal' : ActorMethod<[], boolean>,
  'setEthBalance' : ActorMethod<[number], undefined>,
  'setEthPrice' : ActorMethod<[number], undefined>,
  'setGenesisLocked' : ActorMethod<[boolean], undefined>,
  'setIcpBalance' : ActorMethod<[number], undefined>,
  'setIcpPrice' : ActorMethod<[number], undefined>,
  'setKuramotoR' : ActorMethod<[number], undefined>,
  'setKycEndpoint' : ActorMethod<[string], undefined>,
  'setUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / submitBuilderDirective — submit a natural language directive for parsing
   * / Returns directiveId for subsequent execution
   */
  'submitBuilderDirective' : ActorMethod<[string], string>,
  'tickBeatManual' : ActorMethod<[], bigint>,
  /**
   * / tickBeatManual with protocol gate — creator-only manual beat + gate check
   */
  'tickBeatManualGated' : ActorMethod<
    [],
    { 'beat' : bigint, 'gateOpen' : boolean }
  >,
  'toggleDelegatedSigning' : ActorMethod<[string], boolean>,
  'updateBankAccountRole' : ActorMethod<[string, string], boolean>,
  'updateGrantStatus' : ActorMethod<[string, string], undefined>,
  /**
   * / updateMilestone — creator-only
   * / Updates milestone status and notes by milestone id
   */
  'updateMilestone' : ActorMethod<[string, MilestoneStatus, string], undefined>,
  /**
   * / updateNodeProvider — creator-only
   * / Updates Bad Marine LLC node provider positioning
   */
  'updateNodeProvider' : ActorMethod<[NodeProvider], undefined>,
  /**
   * / updateOrganHealth — called by organ canisters on their own heartbeat
   * / Any external canister implementing reportHealth() submits here.
   */
  'updateOrganHealth' : ActorMethod<[HealthReport], undefined>,
  /**
   * / Withdraw ICP from Creator Reserve — creator only
   */
  'withdrawCreatorIcp' : ActorMethod<[number], boolean>,
  /**
   * / withdrawToExternalWallet — LIBERATOR real ICRC-1 transfer
   * / Called by all three withdrawal UIs. Creator-only. Executes real transfer.
   * / If toPrincipal is "" (empty), defaults to the founder's canonical account ID:
   * /   8c047c715f630bb8824c4831a1b95ad181a4b9264c528131fd5eccc2e4c6b879
   */
  'withdrawToExternalWallet' : ActorMethod<
    [number, string],
    {
      'error' : [] | [string],
      'blockIndex' : [] | [bigint],
      'success' : boolean,
    }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];