const pc={status:null,agents:[],ledgers:[],wallets:[],vaults:[],receipts:[],monetization:[]};
const q=(id)=>document.getElementById(id);
const safe=(v)=>String(v??'').replace(/[&<>'"]/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(path,options={})=>{const r=await fetch(path,{cache:'no-store',headers:{'content-type':'application/json'},...options});if(!r.ok)throw new Error(`${path} ${r.status}`);return r.json()};
const renderJson=(id,value)=>{const el=q(id);if(el)el.textContent=JSON.stringify(value,null,2)};
async function loadPlatform(){try{pc.status=await api('/api/status');pc.agents=(await api('/api/agents')).agents;pc.ledgers=(await api('/api/ledgers')).ledgers;pc.wallets=(await api('/api/wallets')).wallets;pc.vaults=(await api('/api/vaults')).vaults;pc.receipts=(await api('/api/receipts')).receipts;pc.monetization=(await api('/api/monetization')).paths}catch(error){const fallback=await api('../../config/platform/parallax.background-agents.json');pc.status={ok:false,platform:'PARALLAX sample mode',message:'Run pnpm platform:dev for live local API.',error:error.message};pc.agents=fallback.backgroundAgents.map((a)=>({id:a.id,status:'sample',cadence:a.cadence,lastTick:null}));pc.ledgers=[{id:'parallax-paper-ledger',mode:'paper'},{id:'agent-credit-ledger',mode:'paper'},{id:'icp-local-ledger',mode:'testnet'}];pc.wallets=fallback.sampleWallets;pc.vaults=[{vaultId:'pxv_sample_agent_swarm',name:'Sample Agent Swarm Vault',owner:'sample',mode:'paper',prebuilt:{tools:['policy-pack-alpha','receipt-room','ledger-reconciler']},walletSystem:{outsideConnectors:[{id:'evm',status:'sample'},{id:'solana',status:'sample'},{id:'icp',status:'sample'}]}}];pc.receipts=[];pc.monetization=['vault_api_subscription','agent_wallet_metering','receipt_room_enterprise','connector_marketplace','managed_agent_ops','white_label_vaults']}renderPlatform()}
function renderPlatform(){q('virtualServers').innerHTML=['agent-control','vault-wallet-ledger','proof-room','billing-meter'].map((name)=>`<article class="card small"><div class="pill">virtual server</div><h3>${safe(name)}</h3><p>/api routes ready for Node local or Cloudflare Worker.</p></article>`).join('');q('backgroundAgents').innerHTML=pc.agents.map((a)=>`<article class="card small"><div class="pill">${safe(a.status)}</div><h3>${safe(a.id)}</h3><p>${safe(a.cadence)}</p><button data-agent="${safe(a.id)}" class="secondary agentTick">Tick agent</button></article>`).join('');q('ledgerApi').innerHTML=pc.ledgers.map((l)=>`<article class="card small"><h3>${safe(l.id)}</h3><p>${safe(l.mode)} · ${(l.assets||[]).map(safe).join(', ')}</p></article>`).join('');q('apiWallets').innerHTML=pc.wallets.map((w)=>`<article class="card small"><h3>${safe(w.walletId)}</h3><p>${safe(w.agentId)} · ${safe(w.mode)}</p><small>${safe(JSON.stringify(w.balances||{}))}</small></article>`).join('');const vaultEl=q('apiVaults');if(vaultEl)vaultEl.innerHTML=pc.vaults.map((v)=>`<article class="card wide"><div class="pill">vault</div><h3>${safe(v.name||v.vaultId)}</h3><p>${safe(v.owner)} · ${safe(v.mode)} · ${safe(v.vaultId)}</p><small>Connectors: ${(v.walletSystem?.outsideConnectors||[]).map(c=>safe(c.id)).join(', ')}</small><div class="tokens">${(v.prebuilt?.tools||[]).map(t=>`<span>${safe(t)}</span>`).join('')}</div></article>`).join('');const moneyEl=q('monetizationPaths');if(moneyEl)moneyEl.innerHTML=pc.monetization.map((m)=>`<article class="card small"><div class="pill">business path</div><h3>${safe(m)}</h3><p>Monetizable vault/API surface. Pricing remains outside code.</p></article>`).join('');renderJson('apiOutput',{status:pc.status,receipts:pc.receipts.slice(-5)});document.querySelectorAll('.agentTick').forEach((b)=>b.onclick=()=>tickAgent(b.dataset.agent))}
async function createDemoWallet(){const result=await api('/api/wallets',{method:'POST',body:JSON.stringify({agentId:'marketing-demo-agent',owner:'demo-operator',pxusd:25000,pxai:5000})});renderJson('apiOutput',result);await loadPlatform()}
async function createDemoVault(){const result=await api('/api/vaults',{method:'POST',body:JSON.stringify({name:'Customer AI Ops Vault',agentId:'customer-agent-001',owner:'customer-operator',plan:'vault_api_subscription',pxusd:75000,pxai:15000})});renderJson('apiOutput',result);await loadPlatform()}
async function tickAgent(agentId='agent-market-sentinel'){const result=await api('/api/agents/tick',{method:'POST',body:JSON.stringify({agentId})});renderJson('apiOutput',result);await loadPlatform()}
async function sampleTransfer(){const wallets=(await api('/api/wallets')).wallets;let target=wallets.find((w)=>w.walletId!=='pxw_demo_external_agent');if(!target)target=(await api('/api/wallets',{method:'POST',body:JSON.stringify({agentId:'target-agent',owner:'target-operator',pxusd:500})})).wallet;const result=await api('/api/ledger/transfer',{method:'POST',body:JSON.stringify({fromWalletId:'pxw_demo_external_agent',toWalletId:target.walletId,asset:'PXUSD',amount:250})});renderJson('apiOutput',result);await loadPlatform()}
window.createDemoWallet=createDemoWallet;window.createDemoVault=createDemoVault;window.tickBackgroundAgent=()=>tickAgent();window.sampleLedgerTransfer=sampleTransfer;loadPlatform();