"""PARALLAX time series analysis toolkit."""

from .statsmodels_integration import (
    ChangepointResult,
    ForecastResult,
    FrequencyDomainResult,
    FittedTimeSeriesModel,
    MissingStatsmodelsError,
    ModelSelectionResult,
    StateSpaceResult,
    StructuralBreakResult,
    WaveletResult,
    bayesian_changepoint_scores,
    detect_cusum_changepoints,
    ensemble_forecast,
    fit_arima,
    fit_dynamic_linear_model,
    fit_sarima,
    fit_structural_time_series,
    forecast,
    frequency_domain_analysis,
    haar_wavelet_decomposition,
    select_arima_model,
    select_sarima_model,
    structural_break_test,
)

__all__ = [
    "ChangepointResult",
    "ForecastResult",
    "FrequencyDomainResult",
    "FittedTimeSeriesModel",
    "MissingStatsmodelsError",
    "ModelSelectionResult",
    "StateSpaceResult",
    "StructuralBreakResult",
    "WaveletResult",
    "bayesian_changepoint_scores",
    "detect_cusum_changepoints",
    "ensemble_forecast",
    "fit_arima",
    "fit_dynamic_linear_model",
    "fit_sarima",
    "fit_structural_time_series",
    "forecast",
    "frequency_domain_analysis",
    "haar_wavelet_decomposition",
    "select_arima_model",
    "select_sarima_model",
    "structural_break_test",
]
